# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nidaqmx_pb2 as nidaqmx__pb2


class NiDAQmxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/CreateTask',
                request_serializer=nidaqmx__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.CreateTaskResponse.FromString,
                )
        self.ClearTask = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/ClearTask',
                request_serializer=nidaqmx__pb2.ClearTaskRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.ClearTaskResponse.FromString,
                )
        self.StartTask = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/StartTask',
                request_serializer=nidaqmx__pb2.StartTaskRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.StartTaskResponse.FromString,
                )
        self.StopTask = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/StopTask',
                request_serializer=nidaqmx__pb2.StopTaskRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.StopTaskResponse.FromString,
                )
        self.ExportSignal = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/ExportSignal',
                request_serializer=nidaqmx__pb2.ExportSignalRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.ExportSignalResponse.FromString,
                )
        self.GetExtendedErrorInfo = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetExtendedErrorInfo',
                request_serializer=nidaqmx__pb2.GetExtendedErrorInfoRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetExtendedErrorInfoResponse.FromString,
                )
        self.ConnectTerms = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/ConnectTerms',
                request_serializer=nidaqmx__pb2.ConnectTermsRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.ConnectTermsResponse.FromString,
                )
        self.DisconnectTerms = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/DisconnectTerms',
                request_serializer=nidaqmx__pb2.DisconnectTermsRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.DisconnectTermsResponse.FromString,
                )
        self.CfgDigEdgeStartTrig = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/CfgDigEdgeStartTrig',
                request_serializer=nidaqmx__pb2.CfgDigEdgeStartTrigRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.CfgDigEdgeStartTrigResponse.FromString,
                )
        self.CreateCIPulseChanFreq = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/CreateCIPulseChanFreq',
                request_serializer=nidaqmx__pb2.CreateCIPulseChanFreqRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.CreateCIPulseChanFreqResponse.FromString,
                )
        self.ReadCtrFreq = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/ReadCtrFreq',
                request_serializer=nidaqmx__pb2.ReadCtrFreqRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.ReadCtrFreqResponse.FromString,
                )
        self.ReadCtrFreqStream = channel.unary_stream(
                '/nidaqmx_grpc.NiDAQmx/ReadCtrFreqStream',
                request_serializer=nidaqmx__pb2.ReadCtrFreqStreamRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.ReadCtrFreqStreamResponse.FromString,
                )
        self.CreateAIVoltageChan = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/CreateAIVoltageChan',
                request_serializer=nidaqmx__pb2.CreateAIVoltageChanRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.CreateAIVoltageChanResponse.FromString,
                )
        self.CreateAOVoltageChan = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/CreateAOVoltageChan',
                request_serializer=nidaqmx__pb2.CreateAOVoltageChanRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.CreateAOVoltageChanResponse.FromString,
                )
        self.CreateDIChan = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/CreateDIChan',
                request_serializer=nidaqmx__pb2.CreateDIChanRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.CreateDIChanResponse.FromString,
                )
        self.CreateDOChan = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/CreateDOChan',
                request_serializer=nidaqmx__pb2.CreateDOChanRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.CreateDOChanResponse.FromString,
                )
        self.GetChanAttributeUInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetChanAttributeUInt32',
                request_serializer=nidaqmx__pb2.GetChanAttributeUInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetChanAttributeUInt32Response.FromString,
                )
        self.SetChanAttributeUInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetChanAttributeUInt32',
                request_serializer=nidaqmx__pb2.SetChanAttributeUInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetChanAttributeUInt32Response.FromString,
                )
        self.GetChanAttributeInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetChanAttributeInt32',
                request_serializer=nidaqmx__pb2.GetChanAttributeInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetChanAttributeInt32Response.FromString,
                )
        self.SetChanAttributeInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetChanAttributeInt32',
                request_serializer=nidaqmx__pb2.SetChanAttributeInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetChanAttributeInt32Response.FromString,
                )
        self.GetChanAttributeDouble = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetChanAttributeDouble',
                request_serializer=nidaqmx__pb2.GetChanAttributeDoubleRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetChanAttributeDoubleResponse.FromString,
                )
        self.SetChanAttributeDouble = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetChanAttributeDouble',
                request_serializer=nidaqmx__pb2.SetChanAttributeDoubleRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetChanAttributeDoubleResponse.FromString,
                )
        self.GetChanAttributeString = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetChanAttributeString',
                request_serializer=nidaqmx__pb2.GetChanAttributeStringRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetChanAttributeStringResponse.FromString,
                )
        self.SetChanAttributeString = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetChanAttributeString',
                request_serializer=nidaqmx__pb2.SetChanAttributeStringRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetChanAttributeStringResponse.FromString,
                )
        self.GetTimingAttributeUInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetTimingAttributeUInt32',
                request_serializer=nidaqmx__pb2.GetTimingAttributeUInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetTimingAttributeUInt32Response.FromString,
                )
        self.SetTimingAttributeUInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetTimingAttributeUInt32',
                request_serializer=nidaqmx__pb2.SetTimingAttributeUInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetTimingAttributeUInt32Response.FromString,
                )
        self.GetTimingAttributeInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetTimingAttributeInt32',
                request_serializer=nidaqmx__pb2.GetTimingAttributeInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetTimingAttributeInt32Response.FromString,
                )
        self.SetTimingAttributeInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetTimingAttributeInt32',
                request_serializer=nidaqmx__pb2.SetTimingAttributeInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetTimingAttributeInt32Response.FromString,
                )
        self.GetTimingAttributeDouble = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetTimingAttributeDouble',
                request_serializer=nidaqmx__pb2.GetTimingAttributeDoubleRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetTimingAttributeDoubleResponse.FromString,
                )
        self.SetTimingAttributeDouble = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetTimingAttributeDouble',
                request_serializer=nidaqmx__pb2.SetTimingAttributeDoubleRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetTimingAttributeDoubleResponse.FromString,
                )
        self.GetTimingAttributeString = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetTimingAttributeString',
                request_serializer=nidaqmx__pb2.GetTimingAttributeStringRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetTimingAttributeStringResponse.FromString,
                )
        self.SetTimingAttributeString = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetTimingAttributeString',
                request_serializer=nidaqmx__pb2.SetTimingAttributeStringRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetTimingAttributeStringResponse.FromString,
                )
        self.GetRealTimeAttributeUInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetRealTimeAttributeUInt32',
                request_serializer=nidaqmx__pb2.GetRealTimeAttributeUInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetRealTimeAttributeUInt32Response.FromString,
                )
        self.SetRealTimeAttributeUInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetRealTimeAttributeUInt32',
                request_serializer=nidaqmx__pb2.SetRealTimeAttributeUInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetRealTimeAttributeUInt32Response.FromString,
                )
        self.GetRealTimeAttributeInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetRealTimeAttributeInt32',
                request_serializer=nidaqmx__pb2.GetRealTimeAttributeInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetRealTimeAttributeInt32Response.FromString,
                )
        self.SetRealTimeAttributeInt32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetRealTimeAttributeInt32',
                request_serializer=nidaqmx__pb2.SetRealTimeAttributeInt32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetRealTimeAttributeInt32Response.FromString,
                )
        self.GetRealTimeAttributeDouble = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetRealTimeAttributeDouble',
                request_serializer=nidaqmx__pb2.GetRealTimeAttributeDoubleRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetRealTimeAttributeDoubleResponse.FromString,
                )
        self.SetRealTimeAttributeDouble = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetRealTimeAttributeDouble',
                request_serializer=nidaqmx__pb2.SetRealTimeAttributeDoubleRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetRealTimeAttributeDoubleResponse.FromString,
                )
        self.GetRealTimeAttributeString = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/GetRealTimeAttributeString',
                request_serializer=nidaqmx__pb2.GetRealTimeAttributeStringRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.GetRealTimeAttributeStringResponse.FromString,
                )
        self.SetRealTimeAttributeString = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/SetRealTimeAttributeString',
                request_serializer=nidaqmx__pb2.SetRealTimeAttributeStringRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.SetRealTimeAttributeStringResponse.FromString,
                )
        self.ReadDigitalU32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/ReadDigitalU32',
                request_serializer=nidaqmx__pb2.ReadDigitalU32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.ReadDigitalU32Response.FromString,
                )
        self.ReadDigitalU32Stream = channel.unary_stream(
                '/nidaqmx_grpc.NiDAQmx/ReadDigitalU32Stream',
                request_serializer=nidaqmx__pb2.ReadDigitalU32StreamRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.ReadDigitalU32StreamResponse.FromString,
                )
        self.ReadDigitalU16 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/ReadDigitalU16',
                request_serializer=nidaqmx__pb2.ReadDigitalU16Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.ReadDigitalU16Response.FromString,
                )
        self.ReadDigitalU16Stream = channel.unary_stream(
                '/nidaqmx_grpc.NiDAQmx/ReadDigitalU16Stream',
                request_serializer=nidaqmx__pb2.ReadDigitalU16StreamRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.ReadDigitalU16StreamResponse.FromString,
                )
        self.WriteDigitalU32 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/WriteDigitalU32',
                request_serializer=nidaqmx__pb2.WriteDigitalU32Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.WriteDigitalU32Response.FromString,
                )
        self.WriteDigitalU32Stream = channel.stream_unary(
                '/nidaqmx_grpc.NiDAQmx/WriteDigitalU32Stream',
                request_serializer=nidaqmx__pb2.WriteDigitalU32StreamRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.WriteDigitalU32StreamResponse.FromString,
                )
        self.WriteDigitalU16 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/WriteDigitalU16',
                request_serializer=nidaqmx__pb2.WriteDigitalU16Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.WriteDigitalU16Response.FromString,
                )
        self.WriteDigitalU16Stream = channel.stream_unary(
                '/nidaqmx_grpc.NiDAQmx/WriteDigitalU16Stream',
                request_serializer=nidaqmx__pb2.WriteDigitalU16StreamRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.WriteDigitalU16StreamResponse.FromString,
                )
        self.ReadAnalogF64 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/ReadAnalogF64',
                request_serializer=nidaqmx__pb2.ReadAnalogF64Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.ReadAnalogF64Response.FromString,
                )
        self.ReadAnalogF64StreamCodegen = channel.unary_stream(
                '/nidaqmx_grpc.NiDAQmx/ReadAnalogF64StreamCodegen',
                request_serializer=nidaqmx__pb2.ReadAnalogF64StreamCodegenRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.ReadAnalogF64StreamCodegenResponse.FromString,
                )
        self.ReadAnalogF64StreamCustom = channel.unary_stream(
                '/nidaqmx_grpc.NiDAQmx/ReadAnalogF64StreamCustom',
                request_serializer=nidaqmx__pb2.ReadAnalogF64StreamCustomRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.ReadAnalogF64StreamCustomResponse.FromString,
                )
        self.WriteAnalogF64 = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/WriteAnalogF64',
                request_serializer=nidaqmx__pb2.WriteAnalogF64Request.SerializeToString,
                response_deserializer=nidaqmx__pb2.WriteAnalogF64Response.FromString,
                )
        self.WriteAnalogF64StreamCustom = channel.stream_unary(
                '/nidaqmx_grpc.NiDAQmx/WriteAnalogF64StreamCustom',
                request_serializer=nidaqmx__pb2.WriteAnalogF64StreamCustomRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.WriteAnalogF64StreamCustomResponse.FromString,
                )
        self.CfgSampClkTiming = channel.unary_unary(
                '/nidaqmx_grpc.NiDAQmx/CfgSampClkTiming',
                request_serializer=nidaqmx__pb2.CfgSampClkTimingRequest.SerializeToString,
                response_deserializer=nidaqmx__pb2.CfgSampClkTimingResponse.FromString,
                )


class NiDAQmxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExtendedErrorInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectTerms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectTerms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgDigEdgeStartTrig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCIPulseChanFreq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadCtrFreq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadCtrFreqStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAIVoltageChan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAOVoltageChan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDIChan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDOChan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChanAttributeUInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetChanAttributeUInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChanAttributeInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetChanAttributeInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChanAttributeDouble(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetChanAttributeDouble(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChanAttributeString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetChanAttributeString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimingAttributeUInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimingAttributeUInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimingAttributeInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimingAttributeInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimingAttributeDouble(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimingAttributeDouble(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimingAttributeString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimingAttributeString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRealTimeAttributeUInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRealTimeAttributeUInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRealTimeAttributeInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRealTimeAttributeInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRealTimeAttributeDouble(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRealTimeAttributeDouble(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRealTimeAttributeString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRealTimeAttributeString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDigitalU32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDigitalU32Stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDigitalU16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDigitalU16Stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteDigitalU32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteDigitalU32Stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteDigitalU16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteDigitalU16Stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAnalogF64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAnalogF64StreamCodegen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAnalogF64StreamCustom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteAnalogF64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteAnalogF64StreamCustom(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgSampClkTiming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NiDAQmxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=nidaqmx__pb2.CreateTaskRequest.FromString,
                    response_serializer=nidaqmx__pb2.CreateTaskResponse.SerializeToString,
            ),
            'ClearTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearTask,
                    request_deserializer=nidaqmx__pb2.ClearTaskRequest.FromString,
                    response_serializer=nidaqmx__pb2.ClearTaskResponse.SerializeToString,
            ),
            'StartTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTask,
                    request_deserializer=nidaqmx__pb2.StartTaskRequest.FromString,
                    response_serializer=nidaqmx__pb2.StartTaskResponse.SerializeToString,
            ),
            'StopTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTask,
                    request_deserializer=nidaqmx__pb2.StopTaskRequest.FromString,
                    response_serializer=nidaqmx__pb2.StopTaskResponse.SerializeToString,
            ),
            'ExportSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportSignal,
                    request_deserializer=nidaqmx__pb2.ExportSignalRequest.FromString,
                    response_serializer=nidaqmx__pb2.ExportSignalResponse.SerializeToString,
            ),
            'GetExtendedErrorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExtendedErrorInfo,
                    request_deserializer=nidaqmx__pb2.GetExtendedErrorInfoRequest.FromString,
                    response_serializer=nidaqmx__pb2.GetExtendedErrorInfoResponse.SerializeToString,
            ),
            'ConnectTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectTerms,
                    request_deserializer=nidaqmx__pb2.ConnectTermsRequest.FromString,
                    response_serializer=nidaqmx__pb2.ConnectTermsResponse.SerializeToString,
            ),
            'DisconnectTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectTerms,
                    request_deserializer=nidaqmx__pb2.DisconnectTermsRequest.FromString,
                    response_serializer=nidaqmx__pb2.DisconnectTermsResponse.SerializeToString,
            ),
            'CfgDigEdgeStartTrig': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgDigEdgeStartTrig,
                    request_deserializer=nidaqmx__pb2.CfgDigEdgeStartTrigRequest.FromString,
                    response_serializer=nidaqmx__pb2.CfgDigEdgeStartTrigResponse.SerializeToString,
            ),
            'CreateCIPulseChanFreq': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCIPulseChanFreq,
                    request_deserializer=nidaqmx__pb2.CreateCIPulseChanFreqRequest.FromString,
                    response_serializer=nidaqmx__pb2.CreateCIPulseChanFreqResponse.SerializeToString,
            ),
            'ReadCtrFreq': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadCtrFreq,
                    request_deserializer=nidaqmx__pb2.ReadCtrFreqRequest.FromString,
                    response_serializer=nidaqmx__pb2.ReadCtrFreqResponse.SerializeToString,
            ),
            'ReadCtrFreqStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadCtrFreqStream,
                    request_deserializer=nidaqmx__pb2.ReadCtrFreqStreamRequest.FromString,
                    response_serializer=nidaqmx__pb2.ReadCtrFreqStreamResponse.SerializeToString,
            ),
            'CreateAIVoltageChan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAIVoltageChan,
                    request_deserializer=nidaqmx__pb2.CreateAIVoltageChanRequest.FromString,
                    response_serializer=nidaqmx__pb2.CreateAIVoltageChanResponse.SerializeToString,
            ),
            'CreateAOVoltageChan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAOVoltageChan,
                    request_deserializer=nidaqmx__pb2.CreateAOVoltageChanRequest.FromString,
                    response_serializer=nidaqmx__pb2.CreateAOVoltageChanResponse.SerializeToString,
            ),
            'CreateDIChan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDIChan,
                    request_deserializer=nidaqmx__pb2.CreateDIChanRequest.FromString,
                    response_serializer=nidaqmx__pb2.CreateDIChanResponse.SerializeToString,
            ),
            'CreateDOChan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDOChan,
                    request_deserializer=nidaqmx__pb2.CreateDOChanRequest.FromString,
                    response_serializer=nidaqmx__pb2.CreateDOChanResponse.SerializeToString,
            ),
            'GetChanAttributeUInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChanAttributeUInt32,
                    request_deserializer=nidaqmx__pb2.GetChanAttributeUInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.GetChanAttributeUInt32Response.SerializeToString,
            ),
            'SetChanAttributeUInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.SetChanAttributeUInt32,
                    request_deserializer=nidaqmx__pb2.SetChanAttributeUInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.SetChanAttributeUInt32Response.SerializeToString,
            ),
            'GetChanAttributeInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChanAttributeInt32,
                    request_deserializer=nidaqmx__pb2.GetChanAttributeInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.GetChanAttributeInt32Response.SerializeToString,
            ),
            'SetChanAttributeInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.SetChanAttributeInt32,
                    request_deserializer=nidaqmx__pb2.SetChanAttributeInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.SetChanAttributeInt32Response.SerializeToString,
            ),
            'GetChanAttributeDouble': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChanAttributeDouble,
                    request_deserializer=nidaqmx__pb2.GetChanAttributeDoubleRequest.FromString,
                    response_serializer=nidaqmx__pb2.GetChanAttributeDoubleResponse.SerializeToString,
            ),
            'SetChanAttributeDouble': grpc.unary_unary_rpc_method_handler(
                    servicer.SetChanAttributeDouble,
                    request_deserializer=nidaqmx__pb2.SetChanAttributeDoubleRequest.FromString,
                    response_serializer=nidaqmx__pb2.SetChanAttributeDoubleResponse.SerializeToString,
            ),
            'GetChanAttributeString': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChanAttributeString,
                    request_deserializer=nidaqmx__pb2.GetChanAttributeStringRequest.FromString,
                    response_serializer=nidaqmx__pb2.GetChanAttributeStringResponse.SerializeToString,
            ),
            'SetChanAttributeString': grpc.unary_unary_rpc_method_handler(
                    servicer.SetChanAttributeString,
                    request_deserializer=nidaqmx__pb2.SetChanAttributeStringRequest.FromString,
                    response_serializer=nidaqmx__pb2.SetChanAttributeStringResponse.SerializeToString,
            ),
            'GetTimingAttributeUInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimingAttributeUInt32,
                    request_deserializer=nidaqmx__pb2.GetTimingAttributeUInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.GetTimingAttributeUInt32Response.SerializeToString,
            ),
            'SetTimingAttributeUInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimingAttributeUInt32,
                    request_deserializer=nidaqmx__pb2.SetTimingAttributeUInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.SetTimingAttributeUInt32Response.SerializeToString,
            ),
            'GetTimingAttributeInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimingAttributeInt32,
                    request_deserializer=nidaqmx__pb2.GetTimingAttributeInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.GetTimingAttributeInt32Response.SerializeToString,
            ),
            'SetTimingAttributeInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimingAttributeInt32,
                    request_deserializer=nidaqmx__pb2.SetTimingAttributeInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.SetTimingAttributeInt32Response.SerializeToString,
            ),
            'GetTimingAttributeDouble': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimingAttributeDouble,
                    request_deserializer=nidaqmx__pb2.GetTimingAttributeDoubleRequest.FromString,
                    response_serializer=nidaqmx__pb2.GetTimingAttributeDoubleResponse.SerializeToString,
            ),
            'SetTimingAttributeDouble': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimingAttributeDouble,
                    request_deserializer=nidaqmx__pb2.SetTimingAttributeDoubleRequest.FromString,
                    response_serializer=nidaqmx__pb2.SetTimingAttributeDoubleResponse.SerializeToString,
            ),
            'GetTimingAttributeString': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimingAttributeString,
                    request_deserializer=nidaqmx__pb2.GetTimingAttributeStringRequest.FromString,
                    response_serializer=nidaqmx__pb2.GetTimingAttributeStringResponse.SerializeToString,
            ),
            'SetTimingAttributeString': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimingAttributeString,
                    request_deserializer=nidaqmx__pb2.SetTimingAttributeStringRequest.FromString,
                    response_serializer=nidaqmx__pb2.SetTimingAttributeStringResponse.SerializeToString,
            ),
            'GetRealTimeAttributeUInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRealTimeAttributeUInt32,
                    request_deserializer=nidaqmx__pb2.GetRealTimeAttributeUInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.GetRealTimeAttributeUInt32Response.SerializeToString,
            ),
            'SetRealTimeAttributeUInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRealTimeAttributeUInt32,
                    request_deserializer=nidaqmx__pb2.SetRealTimeAttributeUInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.SetRealTimeAttributeUInt32Response.SerializeToString,
            ),
            'GetRealTimeAttributeInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRealTimeAttributeInt32,
                    request_deserializer=nidaqmx__pb2.GetRealTimeAttributeInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.GetRealTimeAttributeInt32Response.SerializeToString,
            ),
            'SetRealTimeAttributeInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRealTimeAttributeInt32,
                    request_deserializer=nidaqmx__pb2.SetRealTimeAttributeInt32Request.FromString,
                    response_serializer=nidaqmx__pb2.SetRealTimeAttributeInt32Response.SerializeToString,
            ),
            'GetRealTimeAttributeDouble': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRealTimeAttributeDouble,
                    request_deserializer=nidaqmx__pb2.GetRealTimeAttributeDoubleRequest.FromString,
                    response_serializer=nidaqmx__pb2.GetRealTimeAttributeDoubleResponse.SerializeToString,
            ),
            'SetRealTimeAttributeDouble': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRealTimeAttributeDouble,
                    request_deserializer=nidaqmx__pb2.SetRealTimeAttributeDoubleRequest.FromString,
                    response_serializer=nidaqmx__pb2.SetRealTimeAttributeDoubleResponse.SerializeToString,
            ),
            'GetRealTimeAttributeString': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRealTimeAttributeString,
                    request_deserializer=nidaqmx__pb2.GetRealTimeAttributeStringRequest.FromString,
                    response_serializer=nidaqmx__pb2.GetRealTimeAttributeStringResponse.SerializeToString,
            ),
            'SetRealTimeAttributeString': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRealTimeAttributeString,
                    request_deserializer=nidaqmx__pb2.SetRealTimeAttributeStringRequest.FromString,
                    response_serializer=nidaqmx__pb2.SetRealTimeAttributeStringResponse.SerializeToString,
            ),
            'ReadDigitalU32': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDigitalU32,
                    request_deserializer=nidaqmx__pb2.ReadDigitalU32Request.FromString,
                    response_serializer=nidaqmx__pb2.ReadDigitalU32Response.SerializeToString,
            ),
            'ReadDigitalU32Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadDigitalU32Stream,
                    request_deserializer=nidaqmx__pb2.ReadDigitalU32StreamRequest.FromString,
                    response_serializer=nidaqmx__pb2.ReadDigitalU32StreamResponse.SerializeToString,
            ),
            'ReadDigitalU16': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDigitalU16,
                    request_deserializer=nidaqmx__pb2.ReadDigitalU16Request.FromString,
                    response_serializer=nidaqmx__pb2.ReadDigitalU16Response.SerializeToString,
            ),
            'ReadDigitalU16Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadDigitalU16Stream,
                    request_deserializer=nidaqmx__pb2.ReadDigitalU16StreamRequest.FromString,
                    response_serializer=nidaqmx__pb2.ReadDigitalU16StreamResponse.SerializeToString,
            ),
            'WriteDigitalU32': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteDigitalU32,
                    request_deserializer=nidaqmx__pb2.WriteDigitalU32Request.FromString,
                    response_serializer=nidaqmx__pb2.WriteDigitalU32Response.SerializeToString,
            ),
            'WriteDigitalU32Stream': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteDigitalU32Stream,
                    request_deserializer=nidaqmx__pb2.WriteDigitalU32StreamRequest.FromString,
                    response_serializer=nidaqmx__pb2.WriteDigitalU32StreamResponse.SerializeToString,
            ),
            'WriteDigitalU16': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteDigitalU16,
                    request_deserializer=nidaqmx__pb2.WriteDigitalU16Request.FromString,
                    response_serializer=nidaqmx__pb2.WriteDigitalU16Response.SerializeToString,
            ),
            'WriteDigitalU16Stream': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteDigitalU16Stream,
                    request_deserializer=nidaqmx__pb2.WriteDigitalU16StreamRequest.FromString,
                    response_serializer=nidaqmx__pb2.WriteDigitalU16StreamResponse.SerializeToString,
            ),
            'ReadAnalogF64': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadAnalogF64,
                    request_deserializer=nidaqmx__pb2.ReadAnalogF64Request.FromString,
                    response_serializer=nidaqmx__pb2.ReadAnalogF64Response.SerializeToString,
            ),
            'ReadAnalogF64StreamCodegen': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadAnalogF64StreamCodegen,
                    request_deserializer=nidaqmx__pb2.ReadAnalogF64StreamCodegenRequest.FromString,
                    response_serializer=nidaqmx__pb2.ReadAnalogF64StreamCodegenResponse.SerializeToString,
            ),
            'ReadAnalogF64StreamCustom': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadAnalogF64StreamCustom,
                    request_deserializer=nidaqmx__pb2.ReadAnalogF64StreamCustomRequest.FromString,
                    response_serializer=nidaqmx__pb2.ReadAnalogF64StreamCustomResponse.SerializeToString,
            ),
            'WriteAnalogF64': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteAnalogF64,
                    request_deserializer=nidaqmx__pb2.WriteAnalogF64Request.FromString,
                    response_serializer=nidaqmx__pb2.WriteAnalogF64Response.SerializeToString,
            ),
            'WriteAnalogF64StreamCustom': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteAnalogF64StreamCustom,
                    request_deserializer=nidaqmx__pb2.WriteAnalogF64StreamCustomRequest.FromString,
                    response_serializer=nidaqmx__pb2.WriteAnalogF64StreamCustomResponse.SerializeToString,
            ),
            'CfgSampClkTiming': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgSampClkTiming,
                    request_deserializer=nidaqmx__pb2.CfgSampClkTimingRequest.FromString,
                    response_serializer=nidaqmx__pb2.CfgSampClkTimingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nidaqmx_grpc.NiDAQmx', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NiDAQmx(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/CreateTask',
            nidaqmx__pb2.CreateTaskRequest.SerializeToString,
            nidaqmx__pb2.CreateTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/ClearTask',
            nidaqmx__pb2.ClearTaskRequest.SerializeToString,
            nidaqmx__pb2.ClearTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/StartTask',
            nidaqmx__pb2.StartTaskRequest.SerializeToString,
            nidaqmx__pb2.StartTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/StopTask',
            nidaqmx__pb2.StopTaskRequest.SerializeToString,
            nidaqmx__pb2.StopTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExportSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/ExportSignal',
            nidaqmx__pb2.ExportSignalRequest.SerializeToString,
            nidaqmx__pb2.ExportSignalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExtendedErrorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetExtendedErrorInfo',
            nidaqmx__pb2.GetExtendedErrorInfoRequest.SerializeToString,
            nidaqmx__pb2.GetExtendedErrorInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/ConnectTerms',
            nidaqmx__pb2.ConnectTermsRequest.SerializeToString,
            nidaqmx__pb2.ConnectTermsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisconnectTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/DisconnectTerms',
            nidaqmx__pb2.DisconnectTermsRequest.SerializeToString,
            nidaqmx__pb2.DisconnectTermsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgDigEdgeStartTrig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/CfgDigEdgeStartTrig',
            nidaqmx__pb2.CfgDigEdgeStartTrigRequest.SerializeToString,
            nidaqmx__pb2.CfgDigEdgeStartTrigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCIPulseChanFreq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/CreateCIPulseChanFreq',
            nidaqmx__pb2.CreateCIPulseChanFreqRequest.SerializeToString,
            nidaqmx__pb2.CreateCIPulseChanFreqResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadCtrFreq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/ReadCtrFreq',
            nidaqmx__pb2.ReadCtrFreqRequest.SerializeToString,
            nidaqmx__pb2.ReadCtrFreqResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadCtrFreqStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/nidaqmx_grpc.NiDAQmx/ReadCtrFreqStream',
            nidaqmx__pb2.ReadCtrFreqStreamRequest.SerializeToString,
            nidaqmx__pb2.ReadCtrFreqStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAIVoltageChan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/CreateAIVoltageChan',
            nidaqmx__pb2.CreateAIVoltageChanRequest.SerializeToString,
            nidaqmx__pb2.CreateAIVoltageChanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAOVoltageChan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/CreateAOVoltageChan',
            nidaqmx__pb2.CreateAOVoltageChanRequest.SerializeToString,
            nidaqmx__pb2.CreateAOVoltageChanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateDIChan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/CreateDIChan',
            nidaqmx__pb2.CreateDIChanRequest.SerializeToString,
            nidaqmx__pb2.CreateDIChanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateDOChan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/CreateDOChan',
            nidaqmx__pb2.CreateDOChanRequest.SerializeToString,
            nidaqmx__pb2.CreateDOChanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChanAttributeUInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetChanAttributeUInt32',
            nidaqmx__pb2.GetChanAttributeUInt32Request.SerializeToString,
            nidaqmx__pb2.GetChanAttributeUInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetChanAttributeUInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetChanAttributeUInt32',
            nidaqmx__pb2.SetChanAttributeUInt32Request.SerializeToString,
            nidaqmx__pb2.SetChanAttributeUInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChanAttributeInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetChanAttributeInt32',
            nidaqmx__pb2.GetChanAttributeInt32Request.SerializeToString,
            nidaqmx__pb2.GetChanAttributeInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetChanAttributeInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetChanAttributeInt32',
            nidaqmx__pb2.SetChanAttributeInt32Request.SerializeToString,
            nidaqmx__pb2.SetChanAttributeInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChanAttributeDouble(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetChanAttributeDouble',
            nidaqmx__pb2.GetChanAttributeDoubleRequest.SerializeToString,
            nidaqmx__pb2.GetChanAttributeDoubleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetChanAttributeDouble(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetChanAttributeDouble',
            nidaqmx__pb2.SetChanAttributeDoubleRequest.SerializeToString,
            nidaqmx__pb2.SetChanAttributeDoubleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChanAttributeString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetChanAttributeString',
            nidaqmx__pb2.GetChanAttributeStringRequest.SerializeToString,
            nidaqmx__pb2.GetChanAttributeStringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetChanAttributeString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetChanAttributeString',
            nidaqmx__pb2.SetChanAttributeStringRequest.SerializeToString,
            nidaqmx__pb2.SetChanAttributeStringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimingAttributeUInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetTimingAttributeUInt32',
            nidaqmx__pb2.GetTimingAttributeUInt32Request.SerializeToString,
            nidaqmx__pb2.GetTimingAttributeUInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTimingAttributeUInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetTimingAttributeUInt32',
            nidaqmx__pb2.SetTimingAttributeUInt32Request.SerializeToString,
            nidaqmx__pb2.SetTimingAttributeUInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimingAttributeInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetTimingAttributeInt32',
            nidaqmx__pb2.GetTimingAttributeInt32Request.SerializeToString,
            nidaqmx__pb2.GetTimingAttributeInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTimingAttributeInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetTimingAttributeInt32',
            nidaqmx__pb2.SetTimingAttributeInt32Request.SerializeToString,
            nidaqmx__pb2.SetTimingAttributeInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimingAttributeDouble(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetTimingAttributeDouble',
            nidaqmx__pb2.GetTimingAttributeDoubleRequest.SerializeToString,
            nidaqmx__pb2.GetTimingAttributeDoubleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTimingAttributeDouble(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetTimingAttributeDouble',
            nidaqmx__pb2.SetTimingAttributeDoubleRequest.SerializeToString,
            nidaqmx__pb2.SetTimingAttributeDoubleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimingAttributeString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetTimingAttributeString',
            nidaqmx__pb2.GetTimingAttributeStringRequest.SerializeToString,
            nidaqmx__pb2.GetTimingAttributeStringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTimingAttributeString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetTimingAttributeString',
            nidaqmx__pb2.SetTimingAttributeStringRequest.SerializeToString,
            nidaqmx__pb2.SetTimingAttributeStringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRealTimeAttributeUInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetRealTimeAttributeUInt32',
            nidaqmx__pb2.GetRealTimeAttributeUInt32Request.SerializeToString,
            nidaqmx__pb2.GetRealTimeAttributeUInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRealTimeAttributeUInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetRealTimeAttributeUInt32',
            nidaqmx__pb2.SetRealTimeAttributeUInt32Request.SerializeToString,
            nidaqmx__pb2.SetRealTimeAttributeUInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRealTimeAttributeInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetRealTimeAttributeInt32',
            nidaqmx__pb2.GetRealTimeAttributeInt32Request.SerializeToString,
            nidaqmx__pb2.GetRealTimeAttributeInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRealTimeAttributeInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetRealTimeAttributeInt32',
            nidaqmx__pb2.SetRealTimeAttributeInt32Request.SerializeToString,
            nidaqmx__pb2.SetRealTimeAttributeInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRealTimeAttributeDouble(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetRealTimeAttributeDouble',
            nidaqmx__pb2.GetRealTimeAttributeDoubleRequest.SerializeToString,
            nidaqmx__pb2.GetRealTimeAttributeDoubleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRealTimeAttributeDouble(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetRealTimeAttributeDouble',
            nidaqmx__pb2.SetRealTimeAttributeDoubleRequest.SerializeToString,
            nidaqmx__pb2.SetRealTimeAttributeDoubleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRealTimeAttributeString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/GetRealTimeAttributeString',
            nidaqmx__pb2.GetRealTimeAttributeStringRequest.SerializeToString,
            nidaqmx__pb2.GetRealTimeAttributeStringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRealTimeAttributeString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/SetRealTimeAttributeString',
            nidaqmx__pb2.SetRealTimeAttributeStringRequest.SerializeToString,
            nidaqmx__pb2.SetRealTimeAttributeStringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadDigitalU32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/ReadDigitalU32',
            nidaqmx__pb2.ReadDigitalU32Request.SerializeToString,
            nidaqmx__pb2.ReadDigitalU32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadDigitalU32Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/nidaqmx_grpc.NiDAQmx/ReadDigitalU32Stream',
            nidaqmx__pb2.ReadDigitalU32StreamRequest.SerializeToString,
            nidaqmx__pb2.ReadDigitalU32StreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadDigitalU16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/ReadDigitalU16',
            nidaqmx__pb2.ReadDigitalU16Request.SerializeToString,
            nidaqmx__pb2.ReadDigitalU16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadDigitalU16Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/nidaqmx_grpc.NiDAQmx/ReadDigitalU16Stream',
            nidaqmx__pb2.ReadDigitalU16StreamRequest.SerializeToString,
            nidaqmx__pb2.ReadDigitalU16StreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteDigitalU32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/WriteDigitalU32',
            nidaqmx__pb2.WriteDigitalU32Request.SerializeToString,
            nidaqmx__pb2.WriteDigitalU32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteDigitalU32Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/nidaqmx_grpc.NiDAQmx/WriteDigitalU32Stream',
            nidaqmx__pb2.WriteDigitalU32StreamRequest.SerializeToString,
            nidaqmx__pb2.WriteDigitalU32StreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteDigitalU16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/WriteDigitalU16',
            nidaqmx__pb2.WriteDigitalU16Request.SerializeToString,
            nidaqmx__pb2.WriteDigitalU16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteDigitalU16Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/nidaqmx_grpc.NiDAQmx/WriteDigitalU16Stream',
            nidaqmx__pb2.WriteDigitalU16StreamRequest.SerializeToString,
            nidaqmx__pb2.WriteDigitalU16StreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadAnalogF64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/ReadAnalogF64',
            nidaqmx__pb2.ReadAnalogF64Request.SerializeToString,
            nidaqmx__pb2.ReadAnalogF64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadAnalogF64StreamCodegen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/nidaqmx_grpc.NiDAQmx/ReadAnalogF64StreamCodegen',
            nidaqmx__pb2.ReadAnalogF64StreamCodegenRequest.SerializeToString,
            nidaqmx__pb2.ReadAnalogF64StreamCodegenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadAnalogF64StreamCustom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/nidaqmx_grpc.NiDAQmx/ReadAnalogF64StreamCustom',
            nidaqmx__pb2.ReadAnalogF64StreamCustomRequest.SerializeToString,
            nidaqmx__pb2.ReadAnalogF64StreamCustomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteAnalogF64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/WriteAnalogF64',
            nidaqmx__pb2.WriteAnalogF64Request.SerializeToString,
            nidaqmx__pb2.WriteAnalogF64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteAnalogF64StreamCustom(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/nidaqmx_grpc.NiDAQmx/WriteAnalogF64StreamCustom',
            nidaqmx__pb2.WriteAnalogF64StreamCustomRequest.SerializeToString,
            nidaqmx__pb2.WriteAnalogF64StreamCustomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgSampClkTiming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidaqmx_grpc.NiDAQmx/CfgSampClkTiming',
            nidaqmx__pb2.CfgSampClkTimingRequest.SerializeToString,
            nidaqmx__pb2.CfgSampClkTimingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
