# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nifpga_pb2 as nifpga__pb2


class NiFpgaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.unary_unary(
                '/nifpga_grpc.NiFpga/Open',
                request_serializer=nifpga__pb2.OpenRequest.SerializeToString,
                response_deserializer=nifpga__pb2.OpenResponse.FromString,
                )
        self.Close = channel.unary_unary(
                '/nifpga_grpc.NiFpga/Close',
                request_serializer=nifpga__pb2.CloseRequest.SerializeToString,
                response_deserializer=nifpga__pb2.CloseResponse.FromString,
                )


class NiFpgaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NiFpgaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=nifpga__pb2.OpenRequest.FromString,
                    response_serializer=nifpga__pb2.OpenResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=nifpga__pb2.CloseRequest.FromString,
                    response_serializer=nifpga__pb2.CloseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nifpga_grpc.NiFpga', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NiFpga(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/Open',
            nifpga__pb2.OpenRequest.SerializeToString,
            nifpga__pb2.OpenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/Close',
            nifpga__pb2.CloseRequest.SerializeToString,
            nifpga__pb2.CloseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
