"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import session_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___NiFpgaAttributes = NiFpgaAttributes
class _NiFpgaAttributes(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[NiFpgaAttributes.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    NIFPGA_ATTRIBUTE_UNSPECIFIED = NiFpgaAttributes.V(0)
class NiFpgaAttributes(metaclass=_NiFpgaAttributes):
    V = typing.NewType('V', builtins.int)
NIFPGA_ATTRIBUTE_UNSPECIFIED = NiFpgaAttributes.V(0)

class OpenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SESSION_NAME_FIELD_NUMBER: builtins.int
    BITFILE_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    RESOURCE_FIELD_NUMBER: builtins.int
    ATTRIBUTE_FIELD_NUMBER: builtins.int
    session_name: typing.Text = ...
    bitfile: typing.Text = ...
    signature: typing.Text = ...
    resource: typing.Text = ...
    attribute: builtins.int = ...

    def __init__(self,
        *,
        session_name : typing.Text = ...,
        bitfile : typing.Text = ...,
        signature : typing.Text = ...,
        resource : typing.Text = ...,
        attribute : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"attribute",b"attribute",u"bitfile",b"bitfile",u"resource",b"resource",u"session_name",b"session_name",u"signature",b"signature"]) -> None: ...
global___OpenRequest = OpenRequest

class OpenResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    status: builtins.int = ...

    @property
    def session(self) -> session_pb2.Session: ...

    def __init__(self,
        *,
        status : builtins.int = ...,
        session : typing.Optional[session_pb2.Session] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"session",b"session"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"session",b"session",u"status",b"status"]) -> None: ...
global___OpenResponse = OpenResponse

class CloseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SESSION_FIELD_NUMBER: builtins.int
    ATTRIBUTE_FIELD_NUMBER: builtins.int
    attribute: builtins.int = ...

    @property
    def session(self) -> session_pb2.Session: ...

    def __init__(self,
        *,
        session : typing.Optional[session_pb2.Session] = ...,
        attribute : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"session",b"session"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"attribute",b"attribute",u"session",b"session"]) -> None: ...
global___CloseRequest = CloseRequest

class CloseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.int = ...

    def __init__(self,
        *,
        status : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> None: ...
global___CloseResponse = CloseResponse
