# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nifpga.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_pb2 as session__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nifpga.proto',
  package='nifpga_grpc',
  syntax='proto3',
  serialized_options=b'\n\022com.ni.grpc.nifpgaB\006NiFpgaP\001\252\002\037NationalInstruments.Grpc.NiFpga',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cnifpga.proto\x12\x0bnifpga_grpc\x1a\rsession.proto\"l\n\x0bOpenRequest\x12\x14\n\x0csession_name\x18\x01 \x01(\t\x12\x0f\n\x07\x62itfile\x18\x02 \x01(\t\x12\x11\n\tsignature\x18\x03 \x01(\t\x12\x10\n\x08resource\x18\x04 \x01(\t\x12\x11\n\tattribute\x18\x05 \x01(\r\"G\n\x0cOpenResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\'\n\x07session\x18\x02 \x01(\x0b\x32\x16.nidevice_grpc.Session\"J\n\x0c\x43loseRequest\x12\'\n\x07session\x18\x01 \x01(\x0b\x32\x16.nidevice_grpc.Session\x12\x11\n\tattribute\x18\x02 \x01(\r\"\x1f\n\rCloseResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05*4\n\x10NiFpgaAttributes\x12 \n\x1cNIFPGA_ATTRIBUTE_UNSPECIFIED\x10\x00\x32\x85\x01\n\x06NiFpga\x12;\n\x04Open\x12\x18.nifpga_grpc.OpenRequest\x1a\x19.nifpga_grpc.OpenResponse\x12>\n\x05\x43lose\x12\x19.nifpga_grpc.CloseRequest\x1a\x1a.nifpga_grpc.CloseResponseB@\n\x12\x63om.ni.grpc.nifpgaB\x06NiFpgaP\x01\xaa\x02\x1fNationalInstruments.Grpc.NiFpgab\x06proto3'
  ,
  dependencies=[session__pb2.DESCRIPTOR,])

_NIFPGAATTRIBUTES = _descriptor.EnumDescriptor(
  name='NiFpgaAttributes',
  full_name='nifpga_grpc.NiFpgaAttributes',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NIFPGA_ATTRIBUTE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=336,
  serialized_end=388,
)
_sym_db.RegisterEnumDescriptor(_NIFPGAATTRIBUTES)

NiFpgaAttributes = enum_type_wrapper.EnumTypeWrapper(_NIFPGAATTRIBUTES)
NIFPGA_ATTRIBUTE_UNSPECIFIED = 0



_OPENREQUEST = _descriptor.Descriptor(
  name='OpenRequest',
  full_name='nifpga_grpc.OpenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_name', full_name='nifpga_grpc.OpenRequest.session_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bitfile', full_name='nifpga_grpc.OpenRequest.bitfile', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='nifpga_grpc.OpenRequest.signature', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource', full_name='nifpga_grpc.OpenRequest.resource', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='nifpga_grpc.OpenRequest.attribute', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=152,
)


_OPENRESPONSE = _descriptor.Descriptor(
  name='OpenResponse',
  full_name='nifpga_grpc.OpenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='nifpga_grpc.OpenResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session', full_name='nifpga_grpc.OpenResponse.session', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=225,
)


_CLOSEREQUEST = _descriptor.Descriptor(
  name='CloseRequest',
  full_name='nifpga_grpc.CloseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='nifpga_grpc.CloseRequest.session', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='nifpga_grpc.CloseRequest.attribute', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=301,
)


_CLOSERESPONSE = _descriptor.Descriptor(
  name='CloseResponse',
  full_name='nifpga_grpc.CloseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='nifpga_grpc.CloseResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=334,
)

_OPENRESPONSE.fields_by_name['session'].message_type = session__pb2._SESSION
_CLOSEREQUEST.fields_by_name['session'].message_type = session__pb2._SESSION
DESCRIPTOR.message_types_by_name['OpenRequest'] = _OPENREQUEST
DESCRIPTOR.message_types_by_name['OpenResponse'] = _OPENRESPONSE
DESCRIPTOR.message_types_by_name['CloseRequest'] = _CLOSEREQUEST
DESCRIPTOR.message_types_by_name['CloseResponse'] = _CLOSERESPONSE
DESCRIPTOR.enum_types_by_name['NiFpgaAttributes'] = _NIFPGAATTRIBUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpenRequest = _reflection.GeneratedProtocolMessageType('OpenRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPENREQUEST,
  '__module__' : 'nifpga_pb2'
  # @@protoc_insertion_point(class_scope:nifpga_grpc.OpenRequest)
  })
_sym_db.RegisterMessage(OpenRequest)

OpenResponse = _reflection.GeneratedProtocolMessageType('OpenResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPENRESPONSE,
  '__module__' : 'nifpga_pb2'
  # @@protoc_insertion_point(class_scope:nifpga_grpc.OpenResponse)
  })
_sym_db.RegisterMessage(OpenResponse)

CloseRequest = _reflection.GeneratedProtocolMessageType('CloseRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEREQUEST,
  '__module__' : 'nifpga_pb2'
  # @@protoc_insertion_point(class_scope:nifpga_grpc.CloseRequest)
  })
_sym_db.RegisterMessage(CloseRequest)

CloseResponse = _reflection.GeneratedProtocolMessageType('CloseResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLOSERESPONSE,
  '__module__' : 'nifpga_pb2'
  # @@protoc_insertion_point(class_scope:nifpga_grpc.CloseResponse)
  })
_sym_db.RegisterMessage(CloseResponse)


DESCRIPTOR._options = None

_NIFPGA = _descriptor.ServiceDescriptor(
  name='NiFpga',
  full_name='nifpga_grpc.NiFpga',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=391,
  serialized_end=524,
  methods=[
  _descriptor.MethodDescriptor(
    name='Open',
    full_name='nifpga_grpc.NiFpga.Open',
    index=0,
    containing_service=None,
    input_type=_OPENREQUEST,
    output_type=_OPENRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Close',
    full_name='nifpga_grpc.NiFpga.Close',
    index=1,
    containing_service=None,
    input_type=_CLOSEREQUEST,
    output_type=_CLOSERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NIFPGA)

DESCRIPTOR.services_by_name['NiFpga'] = _NIFPGA

# @@protoc_insertion_point(module_scope)
