# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nixnet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_pb2 as session__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nixnet.proto',
  package='nixnet_grpc',
  syntax='proto3',
  serialized_options=b'\n\022com.ni.grpc.nixnetB\006NiXnetP\001\252\002\035NationalInstruments.Grpc.Xnet',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cnixnet.proto\x12\x0bnixnet_grpc\x1a\rsession.proto\"\x88\x01\n\x14\x43reateSessionRequest\x12\x14\n\x0csession_name\x18\x01 \x01(\t\x12\x15\n\rdatabase_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63luster_name\x18\x03 \x01(\t\x12\x0c\n\x04list\x18\x04 \x01(\t\x12\x11\n\tinterface\x18\x05 \x01(\t\x12\x0c\n\x04mode\x18\x06 \x01(\r\"P\n\x15\x43reateSessionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\'\n\x07session\x18\x02 \x01(\x0b\x32\x16.nidevice_grpc.Session\"7\n\x0c\x43learRequest\x12\'\n\x07session\x18\x01 \x01(\x0b\x32\x16.nidevice_grpc.Session\"\x1f\n\rClearResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05*4\n\x10NiXnetAttributes\x12 \n\x1cNIXNET_ATTRIBUTE_UNSPECIFIED\x10\x00\x32\xa0\x01\n\x06NiXnet\x12V\n\rCreateSession\x12!.nixnet_grpc.CreateSessionRequest\x1a\".nixnet_grpc.CreateSessionResponse\x12>\n\x05\x43lear\x12\x19.nixnet_grpc.ClearRequest\x1a\x1a.nixnet_grpc.ClearResponseB>\n\x12\x63om.ni.grpc.nixnetB\x06NiXnetP\x01\xaa\x02\x1dNationalInstruments.Grpc.Xnetb\x06proto3'
  ,
  dependencies=[session__pb2.DESCRIPTOR,])

_NIXNETATTRIBUTES = _descriptor.EnumDescriptor(
  name='NiXnetAttributes',
  full_name='nixnet_grpc.NiXnetAttributes',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NIXNET_ATTRIBUTE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=355,
  serialized_end=407,
)
_sym_db.RegisterEnumDescriptor(_NIXNETATTRIBUTES)

NiXnetAttributes = enum_type_wrapper.EnumTypeWrapper(_NIXNETATTRIBUTES)
NIXNET_ATTRIBUTE_UNSPECIFIED = 0



_CREATESESSIONREQUEST = _descriptor.Descriptor(
  name='CreateSessionRequest',
  full_name='nixnet_grpc.CreateSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_name', full_name='nixnet_grpc.CreateSessionRequest.session_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='database_name', full_name='nixnet_grpc.CreateSessionRequest.database_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cluster_name', full_name='nixnet_grpc.CreateSessionRequest.cluster_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='list', full_name='nixnet_grpc.CreateSessionRequest.list', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interface', full_name='nixnet_grpc.CreateSessionRequest.interface', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='nixnet_grpc.CreateSessionRequest.mode', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=181,
)


_CREATESESSIONRESPONSE = _descriptor.Descriptor(
  name='CreateSessionResponse',
  full_name='nixnet_grpc.CreateSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='nixnet_grpc.CreateSessionResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session', full_name='nixnet_grpc.CreateSessionResponse.session', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=263,
)


_CLEARREQUEST = _descriptor.Descriptor(
  name='ClearRequest',
  full_name='nixnet_grpc.ClearRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='nixnet_grpc.ClearRequest.session', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=320,
)


_CLEARRESPONSE = _descriptor.Descriptor(
  name='ClearResponse',
  full_name='nixnet_grpc.ClearResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='nixnet_grpc.ClearResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=353,
)

_CREATESESSIONRESPONSE.fields_by_name['session'].message_type = session__pb2._SESSION
_CLEARREQUEST.fields_by_name['session'].message_type = session__pb2._SESSION
DESCRIPTOR.message_types_by_name['CreateSessionRequest'] = _CREATESESSIONREQUEST
DESCRIPTOR.message_types_by_name['CreateSessionResponse'] = _CREATESESSIONRESPONSE
DESCRIPTOR.message_types_by_name['ClearRequest'] = _CLEARREQUEST
DESCRIPTOR.message_types_by_name['ClearResponse'] = _CLEARRESPONSE
DESCRIPTOR.enum_types_by_name['NiXnetAttributes'] = _NIXNETATTRIBUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateSessionRequest = _reflection.GeneratedProtocolMessageType('CreateSessionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESESSIONREQUEST,
  '__module__' : 'nixnet_pb2'
  # @@protoc_insertion_point(class_scope:nixnet_grpc.CreateSessionRequest)
  })
_sym_db.RegisterMessage(CreateSessionRequest)

CreateSessionResponse = _reflection.GeneratedProtocolMessageType('CreateSessionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESESSIONRESPONSE,
  '__module__' : 'nixnet_pb2'
  # @@protoc_insertion_point(class_scope:nixnet_grpc.CreateSessionResponse)
  })
_sym_db.RegisterMessage(CreateSessionResponse)

ClearRequest = _reflection.GeneratedProtocolMessageType('ClearRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLEARREQUEST,
  '__module__' : 'nixnet_pb2'
  # @@protoc_insertion_point(class_scope:nixnet_grpc.ClearRequest)
  })
_sym_db.RegisterMessage(ClearRequest)

ClearResponse = _reflection.GeneratedProtocolMessageType('ClearResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLEARRESPONSE,
  '__module__' : 'nixnet_pb2'
  # @@protoc_insertion_point(class_scope:nixnet_grpc.ClearResponse)
  })
_sym_db.RegisterMessage(ClearResponse)


DESCRIPTOR._options = None

_NIXNET = _descriptor.ServiceDescriptor(
  name='NiXnet',
  full_name='nixnet_grpc.NiXnet',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=410,
  serialized_end=570,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateSession',
    full_name='nixnet_grpc.NiXnet.CreateSession',
    index=0,
    containing_service=None,
    input_type=_CREATESESSIONREQUEST,
    output_type=_CREATESESSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Clear',
    full_name='nixnet_grpc.NiXnet.Clear',
    index=1,
    containing_service=None,
    input_type=_CLEARREQUEST,
    output_type=_CLEARRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NIXNET)

DESCRIPTOR.services_by_name['NiXnet'] = _NIXNET

# @@protoc_insertion_point(module_scope)
