"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import session_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___NiXnetAttributes = NiXnetAttributes
class _NiXnetAttributes(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[NiXnetAttributes.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    NIXNET_ATTRIBUTE_UNSPECIFIED = NiXnetAttributes.V(0)
class NiXnetAttributes(metaclass=_NiXnetAttributes):
    V = typing.NewType('V', builtins.int)
NIXNET_ATTRIBUTE_UNSPECIFIED = NiXnetAttributes.V(0)

class CreateSessionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SESSION_NAME_FIELD_NUMBER: builtins.int
    DATABASE_NAME_FIELD_NUMBER: builtins.int
    CLUSTER_NAME_FIELD_NUMBER: builtins.int
    LIST_FIELD_NUMBER: builtins.int
    INTERFACE_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    session_name: typing.Text = ...
    database_name: typing.Text = ...
    cluster_name: typing.Text = ...
    list: typing.Text = ...
    interface: typing.Text = ...
    mode: builtins.int = ...

    def __init__(self,
        *,
        session_name : typing.Text = ...,
        database_name : typing.Text = ...,
        cluster_name : typing.Text = ...,
        list : typing.Text = ...,
        interface : typing.Text = ...,
        mode : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"cluster_name",b"cluster_name",u"database_name",b"database_name",u"interface",b"interface",u"list",b"list",u"mode",b"mode",u"session_name",b"session_name"]) -> None: ...
global___CreateSessionRequest = CreateSessionRequest

class CreateSessionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    status: builtins.int = ...

    @property
    def session(self) -> session_pb2.Session: ...

    def __init__(self,
        *,
        status : builtins.int = ...,
        session : typing.Optional[session_pb2.Session] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"session",b"session"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"session",b"session",u"status",b"status"]) -> None: ...
global___CreateSessionResponse = CreateSessionResponse

class ClearRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SESSION_FIELD_NUMBER: builtins.int

    @property
    def session(self) -> session_pb2.Session: ...

    def __init__(self,
        *,
        session : typing.Optional[session_pb2.Session] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"session",b"session"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"session",b"session"]) -> None: ...
global___ClearRequest = ClearRequest

class ClearResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.int = ...

    def __init__(self,
        *,
        status : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> None: ...
global___ClearResponse = ClearResponse
