# -*- coding: utf-8 -*-
enums = {   'ChannelAttributes': {   'values': [   {'name': 'AI_Max', 'value': 6109},
                                           {'name': 'AI_Min', 'value': 6110},
                                           {   'name': 'AI_CustomScaleName',
                                               'value': 6112},
                                           {   'name': 'AI_MeasType',
                                               'value': 1685},
                                           {   'name': 'AI_Voltage_Units',
                                               'value': 4244},
                                           {   'name': 'AI_Voltage_dBRef',
                                               'value': 10672},
                                           {   'name': 'AI_Voltage_ACRMS_Units',
                                               'value': 6114},
                                           {   'name': 'AI_Temp_Units',
                                               'value': 4147},
                                           {   'name': 'AI_Thrmcpl_Type',
                                               'value': 4176},
                                           {   'name': 'AI_Thrmcpl_ScaleType',
                                               'value': 10704},
                                           {   'name': 'AI_Thrmcpl_CJCSrc',
                                               'value': 4149},
                                           {   'name': 'AI_Thrmcpl_CJCVal',
                                               'value': 4150},
                                           {   'name': 'AI_Thrmcpl_CJCChan',
                                               'value': 4148},
                                           {   'name': 'AI_RTD_Type',
                                               'value': 4146},
                                           {'name': 'AI_RTD_R0', 'value': 4144},
                                           {'name': 'AI_RTD_A', 'value': 4112},
                                           {'name': 'AI_RTD_B', 'value': 4113},
                                           {'name': 'AI_RTD_C', 'value': 4115},
                                           {   'name': 'AI_Thrmstr_A',
                                               'value': 6345},
                                           {   'name': 'AI_Thrmstr_B',
                                               'value': 6347},
                                           {   'name': 'AI_Thrmstr_C',
                                               'value': 6346},
                                           {   'name': 'AI_Thrmstr_R1',
                                               'value': 4193},
                                           {   'name': 'AI_ForceReadFromChan',
                                               'value': 6392},
                                           {   'name': 'AI_Current_Units',
                                               'value': 1793},
                                           {   'name': 'AI_Current_ACRMS_Units',
                                               'value': 6115},
                                           {   'name': 'AI_Strain_Units',
                                               'value': 2433},
                                           {   'name': 'AI_StrainGage_ForceReadFromChan',
                                               'value': 12282},
                                           {   'name': 'AI_StrainGage_GageFactor',
                                               'value': 2452},
                                           {   'name': 'AI_StrainGage_PoissonRatio',
                                               'value': 2456},
                                           {   'name': 'AI_StrainGage_Cfg',
                                               'value': 2434},
                                           {   'name': 'AI_RosetteStrainGage_RosetteType',
                                               'value': 12286},
                                           {   'name': 'AI_RosetteStrainGage_Orientation',
                                               'value': 12284},
                                           {   'name': 'AI_RosetteStrainGage_StrainChans',
                                               'value': 12283},
                                           {   'name': 'AI_RosetteStrainGage_RosetteMeasType',
                                               'value': 12285},
                                           {   'name': 'AI_Resistance_Units',
                                               'value': 2389},
                                           {   'name': 'AI_Freq_Units',
                                               'value': 2054},
                                           {   'name': 'AI_Freq_ThreshVoltage',
                                               'value': 2069},
                                           {   'name': 'AI_Freq_Hyst',
                                               'value': 2068},
                                           {   'name': 'AI_LVDT_Units',
                                               'value': 2320},
                                           {   'name': 'AI_LVDT_Sensitivity',
                                               'value': 2361},
                                           {   'name': 'AI_LVDT_SensitivityUnits',
                                               'value': 8602},
                                           {   'name': 'AI_RVDT_Units',
                                               'value': 2167},
                                           {   'name': 'AI_RVDT_Sensitivity',
                                               'value': 2307},
                                           {   'name': 'AI_RVDT_SensitivityUnits',
                                               'value': 8603},
                                           {   'name': 'AI_EddyCurrentProxProbe_Units',
                                               'value': 10944},
                                           {   'name': 'AI_EddyCurrentProxProbe_Sensitivity',
                                               'value': 10942},
                                           {   'name': 'AI_EddyCurrentProxProbe_SensitivityUnits',
                                               'value': 10943},
                                           {   'name': 'AI_SoundPressure_MaxSoundPressureLvl',
                                               'value': 8762},
                                           {   'name': 'AI_SoundPressure_Units',
                                               'value': 5416},
                                           {   'name': 'AI_SoundPressure_dBRef',
                                               'value': 10673},
                                           {   'name': 'AI_Microphone_Sensitivity',
                                               'value': 5430},
                                           {   'name': 'AI_Accel_Units',
                                               'value': 1651},
                                           {   'name': 'AI_Accel_dBRef',
                                               'value': 10674},
                                           {   'name': 'AI_Accel_4WireDCVoltage_Sensitivity',
                                               'value': 12565},
                                           {   'name': 'AI_Accel_4WireDCVoltage_SensitivityUnits',
                                               'value': 12566},
                                           {   'name': 'AI_Accel_Sensitivity',
                                               'value': 1682},
                                           {   'name': 'AI_Accel_SensitivityUnits',
                                               'value': 8604},
                                           {   'name': 'AI_Accel_Charge_Sensitivity',
                                               'value': 12563},
                                           {   'name': 'AI_Accel_Charge_SensitivityUnits',
                                               'value': 12564},
                                           {   'name': 'AI_Velocity_Units',
                                               'value': 12276},
                                           {   'name': 'AI_Velocity_IEPESensor_dBRef',
                                               'value': 12277},
                                           {   'name': 'AI_Velocity_IEPESensor_Sensitivity',
                                               'value': 12278},
                                           {   'name': 'AI_Velocity_IEPESensor_SensitivityUnits',
                                               'value': 12279},
                                           {   'name': 'AI_Force_Units',
                                               'value': 12149},
                                           {   'name': 'AI_Force_IEPESensor_Sensitivity',
                                               'value': 12161},
                                           {   'name': 'AI_Force_IEPESensor_SensitivityUnits',
                                               'value': 12162},
                                           {   'name': 'AI_Pressure_Units',
                                               'value': 12150},
                                           {   'name': 'AI_Torque_Units',
                                               'value': 12151},
                                           {   'name': 'AI_Bridge_Units',
                                               'value': 12178},
                                           {   'name': 'AI_Bridge_ElectricalUnits',
                                               'value': 12167},
                                           {   'name': 'AI_Bridge_PhysicalUnits',
                                               'value': 12168},
                                           {   'name': 'AI_Bridge_ScaleType',
                                               'value': 12169},
                                           {   'name': 'AI_Bridge_TwoPointLin_First_ElectricalVal',
                                               'value': 12170},
                                           {   'name': 'AI_Bridge_TwoPointLin_First_PhysicalVal',
                                               'value': 12171},
                                           {   'name': 'AI_Bridge_TwoPointLin_Second_ElectricalVal',
                                               'value': 12172},
                                           {   'name': 'AI_Bridge_TwoPointLin_Second_PhysicalVal',
                                               'value': 12173},
                                           {   'name': 'AI_Bridge_Table_ElectricalVals',
                                               'value': 12174},
                                           {   'name': 'AI_Bridge_Table_PhysicalVals',
                                               'value': 12175},
                                           {   'name': 'AI_Bridge_Poly_ForwardCoeff',
                                               'value': 12176},
                                           {   'name': 'AI_Bridge_Poly_ReverseCoeff',
                                               'value': 12177},
                                           {   'name': 'AI_Charge_Units',
                                               'value': 12562},
                                           {   'name': 'AI_Is_TEDS',
                                               'value': 10627},
                                           {   'name': 'AI_TEDS_Units',
                                               'value': 8672},
                                           {   'name': 'AI_Coupling',
                                               'value': 100},
                                           {   'name': 'AI_Impedance',
                                               'value': 98},
                                           {   'name': 'AI_TermCfg',
                                               'value': 4247},
                                           {   'name': 'AI_InputSrc',
                                               'value': 8600},
                                           {   'name': 'AI_ResistanceCfg',
                                               'value': 6273},
                                           {   'name': 'AI_LeadWireResistance',
                                               'value': 6126},
                                           {   'name': 'AI_Bridge_Cfg',
                                               'value': 135},
                                           {   'name': 'AI_Bridge_NomResistance',
                                               'value': 6124},
                                           {   'name': 'AI_Bridge_InitialVoltage',
                                               'value': 6125},
                                           {   'name': 'AI_Bridge_InitialRatio',
                                               'value': 12166},
                                           {   'name': 'AI_Bridge_ShuntCal_Enable',
                                               'value': 148},
                                           {   'name': 'AI_Bridge_ShuntCal_Select',
                                               'value': 8661},
                                           {   'name': 'AI_Bridge_ShuntCal_ShuntCalASrc',
                                               'value': 12490},
                                           {   'name': 'AI_Bridge_ShuntCal_GainAdjust',
                                               'value': 6463},
                                           {   'name': 'AI_Bridge_ShuntCal_ShuntCalAResistance',
                                               'value': 12152},
                                           {   'name': 'AI_Bridge_ShuntCal_ShuntCalAActualResistance',
                                               'value': 12153},
                                           {   'name': 'AI_Bridge_ShuntCal_ShuntCalBResistance',
                                               'value': 12154},
                                           {   'name': 'AI_Bridge_ShuntCal_ShuntCalBActualResistance',
                                               'value': 12155},
                                           {   'name': 'AI_Bridge_Balance_CoarsePot',
                                               'value': 6129},
                                           {   'name': 'AI_Bridge_Balance_FinePot',
                                               'value': 6388},
                                           {   'name': 'AI_CurrentShunt_Loc',
                                               'value': 6130},
                                           {   'name': 'AI_CurrentShunt_Resistance',
                                               'value': 6131},
                                           {   'name': 'AI_Excit_Sense',
                                               'value': 12541},
                                           {   'name': 'AI_Excit_Src',
                                               'value': 6132},
                                           {   'name': 'AI_Excit_Val',
                                               'value': 6133},
                                           {   'name': 'AI_Excit_UseForScaling',
                                               'value': 6140},
                                           {   'name': 'AI_Excit_UseMultiplexed',
                                               'value': 8576},
                                           {   'name': 'AI_Excit_ActualVal',
                                               'value': 6275},
                                           {   'name': 'AI_Excit_DCorAC',
                                               'value': 6139},
                                           {   'name': 'AI_Excit_VoltageOrCurrent',
                                               'value': 6134},
                                           {   'name': 'AI_Excit_IdleOutputBehavior',
                                               'value': 12472},
                                           {   'name': 'AI_ACExcit_Freq',
                                               'value': 257},
                                           {   'name': 'AI_ACExcit_SyncEnable',
                                               'value': 258},
                                           {   'name': 'AI_ACExcit_WireMode',
                                               'value': 6349},
                                           {   'name': 'AI_SensorPower_Voltage',
                                               'value': 12649},
                                           {   'name': 'AI_SensorPower_Cfg',
                                               'value': 12650},
                                           {   'name': 'AI_SensorPower_Type',
                                               'value': 12651},
                                           {   'name': 'AI_OpenThrmcplDetectEnable',
                                               'value': 12146},
                                           {   'name': 'AI_Thrmcpl_LeadOffsetVoltage',
                                               'value': 12216},
                                           {'name': 'AI_Atten', 'value': 6145},
                                           {   'name': 'AI_ProbeAtten',
                                               'value': 10888},
                                           {   'name': 'AI_Lowpass_Enable',
                                               'value': 6146},
                                           {   'name': 'AI_Lowpass_CutoffFreq',
                                               'value': 6147},
                                           {   'name': 'AI_Lowpass_SwitchCap_ClkSrc',
                                               'value': 6276},
                                           {   'name': 'AI_Lowpass_SwitchCap_ExtClkFreq',
                                               'value': 6277},
                                           {   'name': 'AI_Lowpass_SwitchCap_ExtClkDiv',
                                               'value': 6278},
                                           {   'name': 'AI_Lowpass_SwitchCap_OutClkDiv',
                                               'value': 6279},
                                           {   'name': 'AI_DigFltr_Enable',
                                               'value': 12477},
                                           {   'name': 'AI_DigFltr_Type',
                                               'value': 12478},
                                           {   'name': 'AI_DigFltr_Response',
                                               'value': 12479},
                                           {   'name': 'AI_DigFltr_Order',
                                               'value': 12480},
                                           {   'name': 'AI_DigFltr_Lowpass_CutoffFreq',
                                               'value': 12481},
                                           {   'name': 'AI_DigFltr_Highpass_CutoffFreq',
                                               'value': 12482},
                                           {   'name': 'AI_DigFltr_Bandpass_CenterFreq',
                                               'value': 12483},
                                           {   'name': 'AI_DigFltr_Bandpass_Width',
                                               'value': 12484},
                                           {   'name': 'AI_DigFltr_Notch_CenterFreq',
                                               'value': 12485},
                                           {   'name': 'AI_DigFltr_Notch_Width',
                                               'value': 12486},
                                           {   'name': 'AI_DigFltr_Coeff',
                                               'value': 12487},
                                           {   'name': 'AI_Filter_Enable',
                                               'value': 12659},
                                           {   'name': 'AI_Filter_Freq',
                                               'value': 12660},
                                           {   'name': 'AI_Filter_Response',
                                               'value': 12661},
                                           {   'name': 'AI_Filter_Order',
                                               'value': 12662},
                                           {   'name': 'AI_FilterDelay',
                                               'value': 12269},
                                           {   'name': 'AI_FilterDelayUnits',
                                               'value': 12401},
                                           {   'name': 'AI_RemoveFilterDelay',
                                               'value': 12221},
                                           {   'name': 'AI_FilterDelayAdjustment',
                                               'value': 12404},
                                           {   'name': 'AI_AveragingWinSize',
                                               'value': 12270},
                                           {   'name': 'AI_ResolutionUnits',
                                               'value': 5988},
                                           {   'name': 'AI_Resolution',
                                               'value': 5989},
                                           {   'name': 'AI_RawSampSize',
                                               'value': 8922},
                                           {   'name': 'AI_RawSampJustification',
                                               'value': 80},
                                           {   'name': 'AI_ADCTimingMode',
                                               'value': 10745},
                                           {   'name': 'AI_ADCCustomTimingMode',
                                               'value': 12139},
                                           {   'name': 'AI_Dither_Enable',
                                               'value': 104},
                                           {   'name': 'AI_ChanCal_HasValidCalInfo',
                                               'value': 8855},
                                           {   'name': 'AI_ChanCal_EnableCal',
                                               'value': 8856},
                                           {   'name': 'AI_ChanCal_ApplyCalIfExp',
                                               'value': 8857},
                                           {   'name': 'AI_ChanCal_ScaleType',
                                               'value': 8860},
                                           {   'name': 'AI_ChanCal_Table_PreScaledVals',
                                               'value': 8861},
                                           {   'name': 'AI_ChanCal_Table_ScaledVals',
                                               'value': 8862},
                                           {   'name': 'AI_ChanCal_Poly_ForwardCoeff',
                                               'value': 8863},
                                           {   'name': 'AI_ChanCal_Poly_ReverseCoeff',
                                               'value': 8864},
                                           {   'name': 'AI_ChanCal_OperatorName',
                                               'value': 8867},
                                           {   'name': 'AI_ChanCal_Desc',
                                               'value': 8868},
                                           {   'name': 'AI_ChanCal_Verif_RefVals',
                                               'value': 8865},
                                           {   'name': 'AI_ChanCal_Verif_AcqVals',
                                               'value': 8866},
                                           {   'name': 'AI_Rng_High',
                                               'value': 6165},
                                           {   'name': 'AI_Rng_Low',
                                               'value': 6166},
                                           {   'name': 'AI_DCOffset',
                                               'value': 10889},
                                           {'name': 'AI_Gain', 'value': 6168},
                                           {   'name': 'AI_SampAndHold_Enable',
                                               'value': 6170},
                                           {   'name': 'AI_AutoZeroMode',
                                               'value': 5984},
                                           {   'name': 'AI_ChopEnable',
                                               'value': 12611},
                                           {   'name': 'AI_DataXferMaxRate',
                                               'value': 12567},
                                           {   'name': 'AI_DataXferMech',
                                               'value': 6177},
                                           {   'name': 'AI_DataXferReqCond',
                                               'value': 6283},
                                           {   'name': 'AI_DataXferCustomThreshold',
                                               'value': 8972},
                                           {   'name': 'AI_UsbXferReqSize',
                                               'value': 10894},
                                           {   'name': 'AI_UsbXferReqCount',
                                               'value': 12288},
                                           {   'name': 'AI_MemMapEnable',
                                               'value': 6284},
                                           {   'name': 'AI_RawDataCompressionType',
                                               'value': 8920},
                                           {   'name': 'AI_LossyLSBRemoval_CompressedSampSize',
                                               'value': 8921},
                                           {   'name': 'AI_DevScalingCoeff',
                                               'value': 6448},
                                           {   'name': 'AI_EnhancedAliasRejectionEnable',
                                               'value': 8852},
                                           {   'name': 'AI_OpenChanDetectEnable',
                                               'value': 12543},
                                           {   'name': 'AI_InputLimitsFaultDetect_UpperLimit',
                                               'value': 12684},
                                           {   'name': 'AI_InputLimitsFaultDetect_LowerLimit',
                                               'value': 12685},
                                           {   'name': 'AI_InputLimitsFaultDetectEnable',
                                               'value': 12686},
                                           {   'name': 'AI_PowerSupplyFaultDetectEnable',
                                               'value': 12689},
                                           {   'name': 'AI_OvercurrentDetectEnable',
                                               'value': 12692},
                                           {'name': 'AO_Max', 'value': 4486},
                                           {'name': 'AO_Min', 'value': 4487},
                                           {   'name': 'AO_CustomScaleName',
                                               'value': 4488},
                                           {   'name': 'AO_OutputType',
                                               'value': 4360},
                                           {   'name': 'AO_Voltage_Units',
                                               'value': 4484},
                                           {   'name': 'AO_Voltage_CurrentLimit',
                                               'value': 10781},
                                           {   'name': 'AO_Current_Units',
                                               'value': 4361},
                                           {   'name': 'AO_FuncGen_Type',
                                               'value': 10776},
                                           {   'name': 'AO_FuncGen_Freq',
                                               'value': 10777},
                                           {   'name': 'AO_FuncGen_Amplitude',
                                               'value': 10778},
                                           {   'name': 'AO_FuncGen_Offset',
                                               'value': 10779},
                                           {   'name': 'AO_FuncGen_Square_DutyCycle',
                                               'value': 10780},
                                           {   'name': 'AO_FuncGen_ModulationType',
                                               'value': 10786},
                                           {   'name': 'AO_FuncGen_FMDeviation',
                                               'value': 10787},
                                           {   'name': 'AO_OutputImpedance',
                                               'value': 5264},
                                           {   'name': 'AO_LoadImpedance',
                                               'value': 289},
                                           {   'name': 'AO_IdleOutputBehavior',
                                               'value': 8768},
                                           {   'name': 'AO_TermCfg',
                                               'value': 6286},
                                           {   'name': 'AO_ResolutionUnits',
                                               'value': 6187},
                                           {   'name': 'AO_Resolution',
                                               'value': 6188},
                                           {   'name': 'AO_DAC_Rng_High',
                                               'value': 6190},
                                           {   'name': 'AO_DAC_Rng_Low',
                                               'value': 6189},
                                           {   'name': 'AO_DAC_Ref_ConnToGnd',
                                               'value': 304},
                                           {   'name': 'AO_DAC_Ref_AllowConnToGnd',
                                               'value': 6192},
                                           {   'name': 'AO_DAC_Ref_Src',
                                               'value': 306},
                                           {   'name': 'AO_DAC_Ref_ExtSrc',
                                               'value': 8786},
                                           {   'name': 'AO_DAC_Ref_Val',
                                               'value': 6194},
                                           {   'name': 'AO_DAC_Offset_Src',
                                               'value': 8787},
                                           {   'name': 'AO_DAC_Offset_ExtSrc',
                                               'value': 8788},
                                           {   'name': 'AO_DAC_Offset_Val',
                                               'value': 8789},
                                           {   'name': 'AO_ReglitchEnable',
                                               'value': 307},
                                           {   'name': 'AO_FilterDelay',
                                               'value': 12405},
                                           {   'name': 'AO_FilterDelayUnits',
                                               'value': 12406},
                                           {   'name': 'AO_FilterDelayAdjustment',
                                               'value': 12402},
                                           {'name': 'AO_Gain', 'value': 280},
                                           {   'name': 'AO_UseOnlyOnBrdMem',
                                               'value': 6202},
                                           {   'name': 'AO_DataXferMech',
                                               'value': 308},
                                           {   'name': 'AO_DataXferReqCond',
                                               'value': 6204},
                                           {   'name': 'AO_UsbXferReqSize',
                                               'value': 10895},
                                           {   'name': 'AO_UsbXferReqCount',
                                               'value': 12289},
                                           {   'name': 'AO_MemMapEnable',
                                               'value': 6287},
                                           {   'name': 'AO_DevScalingCoeff',
                                               'value': 6449},
                                           {   'name': 'AO_EnhancedImageRejectionEnable',
                                               'value': 8769},
                                           {   'name': 'DI_InvertLines',
                                               'value': 1939},
                                           {   'name': 'DI_NumLines',
                                               'value': 8568},
                                           {   'name': 'DI_DigFltr_Enable',
                                               'value': 8662},
                                           {   'name': 'DI_DigFltr_MinPulseWidth',
                                               'value': 8663},
                                           {   'name': 'DI_DigFltr_EnableBusMode',
                                               'value': 12030},
                                           {   'name': 'DI_DigFltr_TimebaseSrc',
                                               'value': 11988},
                                           {   'name': 'DI_DigFltr_TimebaseRate',
                                               'value': 11989},
                                           {   'name': 'DI_DigSync_Enable',
                                               'value': 11990},
                                           {   'name': 'DI_Tristate',
                                               'value': 6288},
                                           {   'name': 'DI_LogicFamily',
                                               'value': 10605},
                                           {   'name': 'DI_DataXferMech',
                                               'value': 8803},
                                           {   'name': 'DI_DataXferReqCond',
                                               'value': 8804},
                                           {   'name': 'DI_UsbXferReqSize',
                                               'value': 10896},
                                           {   'name': 'DI_UsbXferReqCount',
                                               'value': 12290},
                                           {   'name': 'DI_MemMapEnable',
                                               'value': 10602},
                                           {   'name': 'DI_AcquireOn',
                                               'value': 10598},
                                           {   'name': 'DO_OutputDriveType',
                                               'value': 4407},
                                           {   'name': 'DO_InvertLines',
                                               'value': 4403},
                                           {   'name': 'DO_NumLines',
                                               'value': 8569},
                                           {   'name': 'DO_Tristate',
                                               'value': 6387},
                                           {   'name': 'DO_LineStates_StartState',
                                               'value': 10610},
                                           {   'name': 'DO_LineStates_PausedState',
                                               'value': 10599},
                                           {   'name': 'DO_LineStates_DoneState',
                                               'value': 10600},
                                           {   'name': 'DO_LogicFamily',
                                               'value': 10606},
                                           {   'name': 'DO_Overcurrent_Limit',
                                               'value': 10885},
                                           {   'name': 'DO_Overcurrent_AutoReenable',
                                               'value': 10886},
                                           {   'name': 'DO_Overcurrent_ReenablePeriod',
                                               'value': 10887},
                                           {   'name': 'DO_UseOnlyOnBrdMem',
                                               'value': 8805},
                                           {   'name': 'DO_DataXferMech',
                                               'value': 8806},
                                           {   'name': 'DO_DataXferReqCond',
                                               'value': 8807},
                                           {   'name': 'DO_UsbXferReqSize',
                                               'value': 10897},
                                           {   'name': 'DO_UsbXferReqCount',
                                               'value': 12291},
                                           {   'name': 'DO_MemMapEnable',
                                               'value': 10603},
                                           {   'name': 'DO_GenerateOn',
                                               'value': 10601},
                                           {'name': 'CI_Max', 'value': 6300},
                                           {'name': 'CI_Min', 'value': 6301},
                                           {   'name': 'CI_CustomScaleName',
                                               'value': 6302},
                                           {   'name': 'CI_MeasType',
                                               'value': 6304},
                                           {   'name': 'CI_Freq_Units',
                                               'value': 6305},
                                           {   'name': 'CI_Freq_Term',
                                               'value': 6306},
                                           {   'name': 'CI_Freq_TermCfg',
                                               'value': 12439},
                                           {   'name': 'CI_Freq_LogicLvlBehavior',
                                               'value': 12440},
                                           {   'name': 'CI_Freq_ThreshVoltage',
                                               'value': 12715},
                                           {   'name': 'CI_Freq_Hyst',
                                               'value': 12716},
                                           {   'name': 'CI_Freq_DigFltr_Enable',
                                               'value': 8679},
                                           {   'name': 'CI_Freq_DigFltr_MinPulseWidth',
                                               'value': 8680},
                                           {   'name': 'CI_Freq_DigFltr_TimebaseSrc',
                                               'value': 8681},
                                           {   'name': 'CI_Freq_DigFltr_TimebaseRate',
                                               'value': 8682},
                                           {   'name': 'CI_Freq_DigSync_Enable',
                                               'value': 8683},
                                           {   'name': 'CI_Freq_StartingEdge',
                                               'value': 1945},
                                           {   'name': 'CI_Freq_MeasMeth',
                                               'value': 324},
                                           {   'name': 'CI_Freq_EnableAveraging',
                                               'value': 11984},
                                           {   'name': 'CI_Freq_MeasTime',
                                               'value': 325},
                                           {   'name': 'CI_Freq_Div',
                                               'value': 327},
                                           {   'name': 'CI_Period_Units',
                                               'value': 6307},
                                           {   'name': 'CI_Period_Term',
                                               'value': 6308},
                                           {   'name': 'CI_Period_TermCfg',
                                               'value': 12441},
                                           {   'name': 'CI_Period_LogicLvlBehavior',
                                               'value': 12442},
                                           {   'name': 'CI_Period_ThreshVoltage',
                                               'value': 12717},
                                           {   'name': 'CI_Period_Hyst',
                                               'value': 12718},
                                           {   'name': 'CI_Period_DigFltr_Enable',
                                               'value': 8684},
                                           {   'name': 'CI_Period_DigFltr_MinPulseWidth',
                                               'value': 8685},
                                           {   'name': 'CI_Period_DigFltr_TimebaseSrc',
                                               'value': 8686},
                                           {   'name': 'CI_Period_DigFltr_TimebaseRate',
                                               'value': 8687},
                                           {   'name': 'CI_Period_DigSync_Enable',
                                               'value': 8688},
                                           {   'name': 'CI_Period_StartingEdge',
                                               'value': 2130},
                                           {   'name': 'CI_Period_MeasMeth',
                                               'value': 6444},
                                           {   'name': 'CI_Period_EnableAveraging',
                                               'value': 11985},
                                           {   'name': 'CI_Period_MeasTime',
                                               'value': 6445},
                                           {   'name': 'CI_Period_Div',
                                               'value': 6446},
                                           {   'name': 'CI_CountEdges_Term',
                                               'value': 6343},
                                           {   'name': 'CI_CountEdges_TermCfg',
                                               'value': 12443},
                                           {   'name': 'CI_CountEdges_LogicLvlBehavior',
                                               'value': 12444},
                                           {   'name': 'CI_CountEdges_ThreshVoltage',
                                               'value': 12719},
                                           {   'name': 'CI_CountEdges_Hyst',
                                               'value': 12720},
                                           {   'name': 'CI_CountEdges_DigFltr_Enable',
                                               'value': 8694},
                                           {   'name': 'CI_CountEdges_DigFltr_MinPulseWidth',
                                               'value': 8695},
                                           {   'name': 'CI_CountEdges_DigFltr_TimebaseSrc',
                                               'value': 8696},
                                           {   'name': 'CI_CountEdges_DigFltr_TimebaseRate',
                                               'value': 8697},
                                           {   'name': 'CI_CountEdges_DigSync_Enable',
                                               'value': 8698},
                                           {   'name': 'CI_CountEdges_Dir',
                                               'value': 1686},
                                           {   'name': 'CI_CountEdges_DirTerm',
                                               'value': 8673},
                                           {   'name': 'CI_CountEdges_CountDir_TermCfg',
                                               'value': 12445},
                                           {   'name': 'CI_CountEdges_CountDir_LogicLvlBehavior',
                                               'value': 12446},
                                           {   'name': 'CI_CountEdges_CountDir_ThreshVoltage',
                                               'value': 12721},
                                           {   'name': 'CI_CountEdges_CountDir_Hyst',
                                               'value': 12722},
                                           {   'name': 'CI_CountEdges_CountDir_DigFltr_Enable',
                                               'value': 8689},
                                           {   'name': 'CI_CountEdges_CountDir_DigFltr_MinPulseWidth',
                                               'value': 8690},
                                           {   'name': 'CI_CountEdges_CountDir_DigFltr_TimebaseSrc',
                                               'value': 8691},
                                           {   'name': 'CI_CountEdges_CountDir_DigFltr_TimebaseRate',
                                               'value': 8692},
                                           {   'name': 'CI_CountEdges_CountDir_DigSync_Enable',
                                               'value': 8693},
                                           {   'name': 'CI_CountEdges_InitialCnt',
                                               'value': 1688},
                                           {   'name': 'CI_CountEdges_ActiveEdge',
                                               'value': 1687},
                                           {   'name': 'CI_CountEdges_CountReset_Enable',
                                               'value': 12207},
                                           {   'name': 'CI_CountEdges_CountReset_ResetCount',
                                               'value': 12208},
                                           {   'name': 'CI_CountEdges_CountReset_Term',
                                               'value': 12209},
                                           {   'name': 'CI_CountEdges_CountReset_TermCfg',
                                               'value': 12447},
                                           {   'name': 'CI_CountEdges_CountReset_LogicLvlBehavior',
                                               'value': 12448},
                                           {   'name': 'CI_CountEdges_CountReset_ThreshVoltage',
                                               'value': 12723},
                                           {   'name': 'CI_CountEdges_CountReset_Hyst',
                                               'value': 12724},
                                           {   'name': 'CI_CountEdges_CountReset_DigFltr_Enable',
                                               'value': 12211},
                                           {   'name': 'CI_CountEdges_CountReset_DigFltr_MinPulseWidth',
                                               'value': 12212},
                                           {   'name': 'CI_CountEdges_CountReset_DigFltr_TimebaseSrc',
                                               'value': 12213},
                                           {   'name': 'CI_CountEdges_CountReset_DigFltr_TimebaseRate',
                                               'value': 12214},
                                           {   'name': 'CI_CountEdges_CountReset_DigSync_Enable',
                                               'value': 12215},
                                           {   'name': 'CI_CountEdges_CountReset_ActiveEdge',
                                               'value': 12210},
                                           {   'name': 'CI_CountEdges_Gate_Enable',
                                               'value': 12525},
                                           {   'name': 'CI_CountEdges_Gate_Term',
                                               'value': 12526},
                                           {   'name': 'CI_CountEdges_Gate_TermCfg',
                                               'value': 12527},
                                           {   'name': 'CI_CountEdges_Gate_LogicLvlBehavior',
                                               'value': 12528},
                                           {   'name': 'CI_CountEdges_Gate_ThreshVoltage',
                                               'value': 12725},
                                           {   'name': 'CI_CountEdges_Gate_Hyst',
                                               'value': 12726},
                                           {   'name': 'CI_CountEdges_Gate_DigFltrEnable',
                                               'value': 12529},
                                           {   'name': 'CI_CountEdges_Gate_DigFltrMinPulseWidth',
                                               'value': 12530},
                                           {   'name': 'CI_CountEdges_Gate_DigFltrTimebaseSrc',
                                               'value': 12531},
                                           {   'name': 'CI_CountEdges_Gate_DigFltrTimebaseRate',
                                               'value': 12532},
                                           {   'name': 'CI_CountEdges_GateWhen',
                                               'value': 12533},
                                           {   'name': 'CI_DutyCycle_Term',
                                               'value': 12429},
                                           {   'name': 'CI_DutyCycle_TermCfg',
                                               'value': 12449},
                                           {   'name': 'CI_DutyCycle_LogicLvlBehavior',
                                               'value': 12450},
                                           {   'name': 'CI_DutyCycle_DigFltr_Enable',
                                               'value': 12430},
                                           {   'name': 'CI_DutyCycle_DigFltr_MinPulseWidth',
                                               'value': 12431},
                                           {   'name': 'CI_DutyCycle_DigFltr_TimebaseSrc',
                                               'value': 12432},
                                           {   'name': 'CI_DutyCycle_DigFltr_TimebaseRate',
                                               'value': 12433},
                                           {   'name': 'CI_DutyCycle_StartingEdge',
                                               'value': 12434},
                                           {   'name': 'CI_AngEncoder_Units',
                                               'value': 6310},
                                           {   'name': 'CI_AngEncoder_PulsesPerRev',
                                               'value': 2165},
                                           {   'name': 'CI_AngEncoder_InitialAngle',
                                               'value': 2177},
                                           {   'name': 'CI_LinEncoder_Units',
                                               'value': 6313},
                                           {   'name': 'CI_LinEncoder_DistPerPulse',
                                               'value': 2321},
                                           {   'name': 'CI_LinEncoder_InitialPos',
                                               'value': 2325},
                                           {   'name': 'CI_Encoder_DecodingType',
                                               'value': 8678},
                                           {   'name': 'CI_Encoder_AInputTerm',
                                               'value': 8605},
                                           {   'name': 'CI_Encoder_AInputTermCfg',
                                               'value': 12451},
                                           {   'name': 'CI_Encoder_AInputLogicLvlBehavior',
                                               'value': 12452},
                                           {   'name': 'CI_Encoder_AInput_DigFltr_Enable',
                                               'value': 8699},
                                           {   'name': 'CI_Encoder_AInput_DigFltr_MinPulseWidth',
                                               'value': 8700},
                                           {   'name': 'CI_Encoder_AInput_DigFltr_TimebaseSrc',
                                               'value': 8701},
                                           {   'name': 'CI_Encoder_AInput_DigFltr_TimebaseRate',
                                               'value': 8702},
                                           {   'name': 'CI_Encoder_AInput_DigSync_Enable',
                                               'value': 8703},
                                           {   'name': 'CI_Encoder_BInputTerm',
                                               'value': 8606},
                                           {   'name': 'CI_Encoder_BInputTermCfg',
                                               'value': 12453},
                                           {   'name': 'CI_Encoder_BInputLogicLvlBehavior',
                                               'value': 12454},
                                           {   'name': 'CI_Encoder_BInput_DigFltr_Enable',
                                               'value': 8704},
                                           {   'name': 'CI_Encoder_BInput_DigFltr_MinPulseWidth',
                                               'value': 8705},
                                           {   'name': 'CI_Encoder_BInput_DigFltr_TimebaseSrc',
                                               'value': 8706},
                                           {   'name': 'CI_Encoder_BInput_DigFltr_TimebaseRate',
                                               'value': 8707},
                                           {   'name': 'CI_Encoder_BInput_DigSync_Enable',
                                               'value': 8708},
                                           {   'name': 'CI_Encoder_ZInputTerm',
                                               'value': 8607},
                                           {   'name': 'CI_Encoder_ZInputTermCfg',
                                               'value': 12455},
                                           {   'name': 'CI_Encoder_ZInputLogicLvlBehavior',
                                               'value': 12456},
                                           {   'name': 'CI_Encoder_ZInput_DigFltr_Enable',
                                               'value': 8709},
                                           {   'name': 'CI_Encoder_ZInput_DigFltr_MinPulseWidth',
                                               'value': 8710},
                                           {   'name': 'CI_Encoder_ZInput_DigFltr_TimebaseSrc',
                                               'value': 8711},
                                           {   'name': 'CI_Encoder_ZInput_DigFltr_TimebaseRate',
                                               'value': 8712},
                                           {   'name': 'CI_Encoder_ZInput_DigSync_Enable',
                                               'value': 8713},
                                           {   'name': 'CI_Encoder_ZIndexEnable',
                                               'value': 2192},
                                           {   'name': 'CI_Encoder_ZIndexVal',
                                               'value': 2184},
                                           {   'name': 'CI_Encoder_ZIndexPhase',
                                               'value': 2185},
                                           {   'name': 'CI_PulseWidth_Units',
                                               'value': 2083},
                                           {   'name': 'CI_PulseWidth_Term',
                                               'value': 6314},
                                           {   'name': 'CI_PulseWidth_TermCfg',
                                               'value': 12457},
                                           {   'name': 'CI_PulseWidth_LogicLvlBehavior',
                                               'value': 12458},
                                           {   'name': 'CI_PulseWidth_DigFltr_Enable',
                                               'value': 8714},
                                           {   'name': 'CI_PulseWidth_DigFltr_MinPulseWidth',
                                               'value': 8715},
                                           {   'name': 'CI_PulseWidth_DigFltr_TimebaseSrc',
                                               'value': 8716},
                                           {   'name': 'CI_PulseWidth_DigFltr_TimebaseRate',
                                               'value': 8717},
                                           {   'name': 'CI_PulseWidth_DigSync_Enable',
                                               'value': 8718},
                                           {   'name': 'CI_PulseWidth_StartingEdge',
                                               'value': 2085},
                                           {   'name': 'CI_Timestamp_Units',
                                               'value': 8883},
                                           {   'name': 'CI_Timestamp_InitialSeconds',
                                               'value': 8884},
                                           {   'name': 'CI_GPS_SyncMethod',
                                               'value': 4242},
                                           {   'name': 'CI_GPS_SyncSrc',
                                               'value': 4243},
                                           {   'name': 'CI_Velocity_AngEncoder_Units',
                                               'value': 12504},
                                           {   'name': 'CI_Velocity_AngEncoder_PulsesPerRev',
                                               'value': 12505},
                                           {   'name': 'CI_Velocity_LinEncoder_Units',
                                               'value': 12506},
                                           {   'name': 'CI_Velocity_LinEncoder_DistPerPulse',
                                               'value': 12507},
                                           {   'name': 'CI_Velocity_Encoder_DecodingType',
                                               'value': 12508},
                                           {   'name': 'CI_Velocity_Encoder_AInputTerm',
                                               'value': 12509},
                                           {   'name': 'CI_Velocity_Encoder_AInputTermCfg',
                                               'value': 12510},
                                           {   'name': 'CI_Velocity_Encoder_AInputLogicLvlBehavior',
                                               'value': 12511},
                                           {   'name': 'CI_Velocity_Encoder_AInputDigFltr_Enable',
                                               'value': 12512},
                                           {   'name': 'CI_Velocity_Encoder_AInputDigFltr_MinPulseWidth',
                                               'value': 12513},
                                           {   'name': 'CI_Velocity_Encoder_AInputDigFltr_TimebaseSrc',
                                               'value': 12514},
                                           {   'name': 'CI_Velocity_Encoder_AInputDigFltr_TimebaseRate',
                                               'value': 12515},
                                           {   'name': 'CI_Velocity_Encoder_BInputTerm',
                                               'value': 12516},
                                           {   'name': 'CI_Velocity_Encoder_BInputTermCfg',
                                               'value': 12517},
                                           {   'name': 'CI_Velocity_Encoder_BInputLogicLvlBehavior',
                                               'value': 12518},
                                           {   'name': 'CI_Velocity_Encoder_BInputDigFltr_Enable',
                                               'value': 12519},
                                           {   'name': 'CI_Velocity_Encoder_BInputDigFltr_MinPulseWidth',
                                               'value': 12520},
                                           {   'name': 'CI_Velocity_Encoder_BInputDigFltr_TimebaseSrc',
                                               'value': 12521},
                                           {   'name': 'CI_Velocity_Encoder_BInputDigFltr_TimebaseRate',
                                               'value': 12522},
                                           {   'name': 'CI_Velocity_MeasTime',
                                               'value': 12523},
                                           {   'name': 'CI_Velocity_Div',
                                               'value': 12524},
                                           {   'name': 'CI_TwoEdgeSep_Units',
                                               'value': 6316},
                                           {   'name': 'CI_TwoEdgeSep_FirstTerm',
                                               'value': 6317},
                                           {   'name': 'CI_TwoEdgeSep_FirstTermCfg',
                                               'value': 12459},
                                           {   'name': 'CI_TwoEdgeSep_FirstLogicLvlBehavior',
                                               'value': 12460},
                                           {   'name': 'CI_TwoEdgeSep_First_DigFltr_Enable',
                                               'value': 8719},
                                           {   'name': 'CI_TwoEdgeSep_First_DigFltr_MinPulseWidth',
                                               'value': 8720},
                                           {   'name': 'CI_TwoEdgeSep_First_DigFltr_TimebaseSrc',
                                               'value': 8721},
                                           {   'name': 'CI_TwoEdgeSep_First_DigFltr_TimebaseRate',
                                               'value': 8722},
                                           {   'name': 'CI_TwoEdgeSep_First_DigSync_Enable',
                                               'value': 8723},
                                           {   'name': 'CI_TwoEdgeSep_FirstEdge',
                                               'value': 2099},
                                           {   'name': 'CI_TwoEdgeSep_SecondTerm',
                                               'value': 6318},
                                           {   'name': 'CI_TwoEdgeSep_SecondTermCfg',
                                               'value': 12461},
                                           {   'name': 'CI_TwoEdgeSep_SecondLogicLvlBehavior',
                                               'value': 12462},
                                           {   'name': 'CI_TwoEdgeSep_Second_DigFltr_Enable',
                                               'value': 8724},
                                           {   'name': 'CI_TwoEdgeSep_Second_DigFltr_MinPulseWidth',
                                               'value': 8725},
                                           {   'name': 'CI_TwoEdgeSep_Second_DigFltr_TimebaseSrc',
                                               'value': 8726},
                                           {   'name': 'CI_TwoEdgeSep_Second_DigFltr_TimebaseRate',
                                               'value': 8727},
                                           {   'name': 'CI_TwoEdgeSep_Second_DigSync_Enable',
                                               'value': 8728},
                                           {   'name': 'CI_TwoEdgeSep_SecondEdge',
                                               'value': 2100},
                                           {   'name': 'CI_SemiPeriod_Units',
                                               'value': 6319},
                                           {   'name': 'CI_SemiPeriod_Term',
                                               'value': 6320},
                                           {   'name': 'CI_SemiPeriod_TermCfg',
                                               'value': 12463},
                                           {   'name': 'CI_SemiPeriod_LogicLvlBehavior',
                                               'value': 12464},
                                           {   'name': 'CI_SemiPeriod_DigFltr_Enable',
                                               'value': 8729},
                                           {   'name': 'CI_SemiPeriod_DigFltr_MinPulseWidth',
                                               'value': 8730},
                                           {   'name': 'CI_SemiPeriod_DigFltr_TimebaseSrc',
                                               'value': 8731},
                                           {   'name': 'CI_SemiPeriod_DigFltr_TimebaseRate',
                                               'value': 8732},
                                           {   'name': 'CI_SemiPeriod_DigSync_Enable',
                                               'value': 8733},
                                           {   'name': 'CI_SemiPeriod_StartingEdge',
                                               'value': 8958},
                                           {   'name': 'CI_Pulse_Freq_Units',
                                               'value': 12043},
                                           {   'name': 'CI_Pulse_Freq_Term',
                                               'value': 12036},
                                           {   'name': 'CI_Pulse_Freq_TermCfg',
                                               'value': 12465},
                                           {   'name': 'CI_Pulse_Freq_LogicLvlBehavior',
                                               'value': 12466},
                                           {   'name': 'CI_Pulse_Freq_DigFltr_Enable',
                                               'value': 12038},
                                           {   'name': 'CI_Pulse_Freq_DigFltr_MinPulseWidth',
                                               'value': 12039},
                                           {   'name': 'CI_Pulse_Freq_DigFltr_TimebaseSrc',
                                               'value': 12040},
                                           {   'name': 'CI_Pulse_Freq_DigFltr_TimebaseRate',
                                               'value': 12041},
                                           {   'name': 'CI_Pulse_Freq_DigSync_Enable',
                                               'value': 12042},
                                           {   'name': 'CI_Pulse_Freq_Start_Edge',
                                               'value': 12037},
                                           {   'name': 'CI_Pulse_Time_Units',
                                               'value': 12051},
                                           {   'name': 'CI_Pulse_Time_Term',
                                               'value': 12044},
                                           {   'name': 'CI_Pulse_Time_TermCfg',
                                               'value': 12467},
                                           {   'name': 'CI_Pulse_Time_LogicLvlBehavior',
                                               'value': 12468},
                                           {   'name': 'CI_Pulse_Time_DigFltr_Enable',
                                               'value': 12046},
                                           {   'name': 'CI_Pulse_Time_DigFltr_MinPulseWidth',
                                               'value': 12047},
                                           {   'name': 'CI_Pulse_Time_DigFltr_TimebaseSrc',
                                               'value': 12048},
                                           {   'name': 'CI_Pulse_Time_DigFltr_TimebaseRate',
                                               'value': 12049},
                                           {   'name': 'CI_Pulse_Time_DigSync_Enable',
                                               'value': 12050},
                                           {   'name': 'CI_Pulse_Time_StartEdge',
                                               'value': 12045},
                                           {   'name': 'CI_Pulse_Ticks_Term',
                                               'value': 12052},
                                           {   'name': 'CI_Pulse_Ticks_TermCfg',
                                               'value': 12469},
                                           {   'name': 'CI_Pulse_Ticks_LogicLvlBehavior',
                                               'value': 12470},
                                           {   'name': 'CI_Pulse_Ticks_DigFltr_Enable',
                                               'value': 12054},
                                           {   'name': 'CI_Pulse_Ticks_DigFltr_MinPulseWidth',
                                               'value': 12055},
                                           {   'name': 'CI_Pulse_Ticks_DigFltr_TimebaseSrc',
                                               'value': 12056},
                                           {   'name': 'CI_Pulse_Ticks_DigFltr_TimebaseRate',
                                               'value': 12057},
                                           {   'name': 'CI_Pulse_Ticks_DigSync_Enable',
                                               'value': 12058},
                                           {   'name': 'CI_Pulse_Ticks_StartEdge',
                                               'value': 12053},
                                           {   'name': 'CI_CtrTimebaseSrc',
                                               'value': 323},
                                           {   'name': 'CI_CtrTimebaseRate',
                                               'value': 6322},
                                           {   'name': 'CI_CtrTimebaseActiveEdge',
                                               'value': 322},
                                           {   'name': 'CI_CtrTimebase_DigFltr_Enable',
                                               'value': 8817},
                                           {   'name': 'CI_CtrTimebase_DigFltr_MinPulseWidth',
                                               'value': 8818},
                                           {   'name': 'CI_CtrTimebase_DigFltr_TimebaseSrc',
                                               'value': 8819},
                                           {   'name': 'CI_CtrTimebase_DigFltr_TimebaseRate',
                                               'value': 8820},
                                           {   'name': 'CI_CtrTimebase_DigSync_Enable',
                                               'value': 8821},
                                           {   'name': 'CI_ThreshVoltage',
                                               'value': 12471},
                                           {   'name': 'CI_Filter_Enable',
                                               'value': 12727},
                                           {   'name': 'CI_Filter_Freq',
                                               'value': 12728},
                                           {   'name': 'CI_Filter_Response',
                                               'value': 12729},
                                           {   'name': 'CI_Filter_Order',
                                               'value': 12730},
                                           {   'name': 'CI_FilterDelay',
                                               'value': 12731},
                                           {   'name': 'CI_FilterDelayUnits',
                                               'value': 12732},
                                           {'name': 'CI_Count', 'value': 328},
                                           {   'name': 'CI_OutputState',
                                               'value': 329},
                                           {   'name': 'CI_TCReached',
                                               'value': 336},
                                           {   'name': 'CI_CtrTimebaseMasterTimebaseDiv',
                                               'value': 6323},
                                           {   'name': 'CI_SampClkOverrunBehavior',
                                               'value': 12435},
                                           {   'name': 'CI_SampClkOverrunSentinelVal',
                                               'value': 12436},
                                           {   'name': 'CI_DataXferMech',
                                               'value': 512},
                                           {   'name': 'CI_DataXferReqCond',
                                               'value': 12027},
                                           {   'name': 'CI_UsbXferReqSize',
                                               'value': 10898},
                                           {   'name': 'CI_UsbXferReqCount',
                                               'value': 12292},
                                           {   'name': 'CI_MemMapEnable',
                                               'value': 11986},
                                           {   'name': 'CI_NumPossiblyInvalidSamps',
                                               'value': 6460},
                                           {   'name': 'CI_DupCountPrevent',
                                               'value': 8620},
                                           {   'name': 'CI_Prescaler',
                                               'value': 8761},
                                           {   'name': 'CI_MaxMeasPeriod',
                                               'value': 12437},
                                           {   'name': 'CO_OutputType',
                                               'value': 6325},
                                           {   'name': 'CO_Pulse_IdleState',
                                               'value': 4464},
                                           {   'name': 'CO_Pulse_Term',
                                               'value': 6369},
                                           {   'name': 'CO_Pulse_Time_Units',
                                               'value': 6358},
                                           {   'name': 'CO_Pulse_HighTime',
                                               'value': 6330},
                                           {   'name': 'CO_Pulse_LowTime',
                                               'value': 6331},
                                           {   'name': 'CO_Pulse_Time_InitialDelay',
                                               'value': 6332},
                                           {   'name': 'CO_Pulse_DutyCyc',
                                               'value': 4470},
                                           {   'name': 'CO_Pulse_Freq_Units',
                                               'value': 6357},
                                           {   'name': 'CO_Pulse_Freq',
                                               'value': 4472},
                                           {   'name': 'CO_Pulse_Freq_InitialDelay',
                                               'value': 665},
                                           {   'name': 'CO_Pulse_HighTicks',
                                               'value': 4457},
                                           {   'name': 'CO_Pulse_LowTicks',
                                               'value': 4465},
                                           {   'name': 'CO_Pulse_Ticks_InitialDelay',
                                               'value': 664},
                                           {   'name': 'CO_CtrTimebaseSrc',
                                               'value': 825},
                                           {   'name': 'CO_CtrTimebaseRate',
                                               'value': 6338},
                                           {   'name': 'CO_CtrTimebaseActiveEdge',
                                               'value': 833},
                                           {   'name': 'CO_CtrTimebase_DigFltr_Enable',
                                               'value': 8822},
                                           {   'name': 'CO_CtrTimebase_DigFltr_MinPulseWidth',
                                               'value': 8823},
                                           {   'name': 'CO_CtrTimebase_DigFltr_TimebaseSrc',
                                               'value': 8824},
                                           {   'name': 'CO_CtrTimebase_DigFltr_TimebaseRate',
                                               'value': 8825},
                                           {   'name': 'CO_CtrTimebase_DigSync_Enable',
                                               'value': 8826},
                                           {'name': 'CO_Count', 'value': 659},
                                           {   'name': 'CO_OutputState',
                                               'value': 660},
                                           {   'name': 'CO_AutoIncrCnt',
                                               'value': 661},
                                           {   'name': 'CO_CtrTimebaseMasterTimebaseDiv',
                                               'value': 6339},
                                           {   'name': 'CO_PulseDone',
                                               'value': 6414},
                                           {   'name': 'CO_EnableInitialDelayOnRetrigger',
                                               'value': 11977},
                                           {   'name': 'CO_ConstrainedGenMode',
                                               'value': 10738},
                                           {   'name': 'CO_UseOnlyOnBrdMem',
                                               'value': 11979},
                                           {   'name': 'CO_DataXferMech',
                                               'value': 11980},
                                           {   'name': 'CO_DataXferReqCond',
                                               'value': 11981},
                                           {   'name': 'CO_UsbXferReqSize',
                                               'value': 10899},
                                           {   'name': 'CO_UsbXferReqCount',
                                               'value': 12293},
                                           {   'name': 'CO_MemMapEnable',
                                               'value': 11987},
                                           {   'name': 'CO_Prescaler',
                                               'value': 8813},
                                           {   'name': 'CO_RdyForNewVal',
                                               'value': 8959},
                                           {'name': 'ChanType', 'value': 6271},
                                           {   'name': 'PhysicalChanName',
                                               'value': 6389},
                                           {'name': 'ChanDescr', 'value': 6438},
                                           {   'name': 'ChanIsGlobal',
                                               'value': 8964},
                                           {   'name': 'Chan_SyncUnlockBehavior',
                                               'value': 12604}]},
    'RealTimeAttributes': {   'values': [   {   'name': 'RealTime_ConvLateErrorsToWarnings',
                                                'value': 8942},
                                            {   'name': 'RealTime_NumOfWarmupIters',
                                                'value': 8941},
                                            {   'name': 'RealTime_WaitForNextSampClkWaitMode',
                                                'value': 8943},
                                            {   'name': 'RealTime_ReportMissedSamp',
                                                'value': 8985},
                                            {   'name': 'RealTime_WriteRecoveryMode',
                                                'value': 8986}]},
    'TimingAttributes': {   'values': [   {   'name': 'SampQuant_SampMode',
                                              'value': 4864},
                                          {   'name': 'SampQuant_SampPerChan',
                                              'value': 4880},
                                          {   'name': 'SampTimingType',
                                              'value': 4935},
                                          {   'name': 'SampClk_Rate',
                                              'value': 4932},
                                          {   'name': 'SampClk_MaxRate',
                                              'value': 8904},
                                          {   'name': 'SampClk_Src',
                                              'value': 6226},
                                          {   'name': 'SampClk_ActiveEdge',
                                              'value': 4865},
                                          {   'name': 'SampClk_OverrunBehavior',
                                              'value': 12028},
                                          {   'name': 'SampClk_UnderflowBehavior',
                                              'value': 10593},
                                          {   'name': 'SampClk_TimebaseDiv',
                                              'value': 6379},
                                          {   'name': 'SampClk_Term',
                                              'value': 12059},
                                          {   'name': 'SampClk_Timebase_Rate',
                                              'value': 4867},
                                          {   'name': 'SampClk_Timebase_Src',
                                              'value': 4872},
                                          {   'name': 'SampClk_Timebase_ActiveEdge',
                                              'value': 6380},
                                          {   'name': 'SampClk_Timebase_MasterTimebaseDiv',
                                              'value': 4869},
                                          {   'name': 'SampClkTimebase_Term',
                                              'value': 12060},
                                          {   'name': 'SampClk_DigFltr_Enable',
                                              'value': 8734},
                                          {   'name': 'SampClk_DigFltr_MinPulseWidth',
                                              'value': 8735},
                                          {   'name': 'SampClk_DigFltr_TimebaseSrc',
                                              'value': 8736},
                                          {   'name': 'SampClk_DigFltr_TimebaseRate',
                                              'value': 8737},
                                          {   'name': 'SampClk_DigSync_Enable',
                                              'value': 8738},
                                          {   'name': 'SampClk_WriteWfm_UseInitialWfmDT',
                                              'value': 12540},
                                          {   'name': 'Hshk_DelayAfterXfer',
                                              'value': 8898},
                                          {   'name': 'Hshk_StartCond',
                                              'value': 8899},
                                          {   'name': 'Hshk_SampleInputDataWhen',
                                              'value': 8900},
                                          {   'name': 'ChangeDetect_DI_RisingEdgePhysicalChans',
                                              'value': 8597},
                                          {   'name': 'ChangeDetect_DI_FallingEdgePhysicalChans',
                                              'value': 8598},
                                          {   'name': 'ChangeDetect_DI_Tristate',
                                              'value': 12026},
                                          {   'name': 'OnDemand_SimultaneousAOEnable',
                                              'value': 8608},
                                          {   'name': 'Implicit_UnderflowBehavior',
                                              'value': 12029},
                                          {   'name': 'AIConv_Rate',
                                              'value': 6216},
                                          {   'name': 'AIConv_MaxRate',
                                              'value': 8905},
                                          {'name': 'AIConv_Src', 'value': 5378},
                                          {   'name': 'AIConv_ActiveEdge',
                                              'value': 6227},
                                          {   'name': 'AIConv_TimebaseDiv',
                                              'value': 4917},
                                          {   'name': 'AIConv_Timebase_Src',
                                              'value': 4921},
                                          {   'name': 'DelayFromSampClk_DelayUnits',
                                              'value': 4868},
                                          {   'name': 'DelayFromSampClk_Delay',
                                              'value': 4887},
                                          {   'name': 'AIConv_DigFltr_Enable',
                                              'value': 11996},
                                          {   'name': 'AIConv_DigFltr_MinPulseWidth',
                                              'value': 11997},
                                          {   'name': 'AIConv_DigFltr_TimebaseSrc',
                                              'value': 11998},
                                          {   'name': 'AIConv_DigFltr_TimebaseRate',
                                              'value': 11999},
                                          {   'name': 'AIConv_DigSync_Enable',
                                              'value': 12000},
                                          {   'name': 'MasterTimebase_Rate',
                                              'value': 5269},
                                          {   'name': 'MasterTimebase_Src',
                                              'value': 4931},
                                          {   'name': 'RefClk_Rate',
                                              'value': 4885},
                                          {'name': 'RefClk_Src', 'value': 4886},
                                          {   'name': 'SyncPulse_Type',
                                              'value': 12598},
                                          {   'name': 'SyncPulse_Src',
                                              'value': 8765},
                                          {   'name': 'SyncPulse_Time_When',
                                              'value': 12599},
                                          {   'name': 'SyncPulse_Time_Timescale',
                                              'value': 12600},
                                          {   'name': 'SyncPulse_SyncTime',
                                              'value': 8766},
                                          {   'name': 'SyncPulse_MinDelayToStart',
                                              'value': 8767},
                                          {   'name': 'SyncPulse_ResetTime',
                                              'value': 12156},
                                          {   'name': 'SyncPulse_ResetDelay',
                                              'value': 12157},
                                          {   'name': 'SyncPulse_Term',
                                              'value': 12165},
                                          {   'name': 'SyncClk_Interval',
                                              'value': 12158},
                                          {   'name': 'SampTimingEngine',
                                              'value': 10790},
                                          {   'name': 'FirstSampTimestamp_Enable',
                                              'value': 12601},
                                          {   'name': 'FirstSampTimestamp_Timescale',
                                              'value': 12603},
                                          {   'name': 'FirstSampTimestamp_Val',
                                              'value': 12602},
                                          {   'name': 'FirstSampClk_When',
                                              'value': 12674},
                                          {   'name': 'FirstSampClk_Timescale',
                                              'value': 12675},
                                          {   'name': 'FirstSampClk_Offset',
                                              'value': 12714}]}}
